In [1]:
# Supress Warnings

import warnings
warnings.filterwarnings('ignore')

In [2]:
# Import the numpy and pandas packages

import numpy as np
import pandas as pd

## Task 1: Reading and Inspection

-  ### Subtask 1.1: Import and read

Import and read the movie database. Store it in a variable called `movies`.

In [3]:
movies = pd.read_csv(r'Movie+Assignment+Data (1).csv')
# Write your code for importing the csv file here
movies

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

-  ### Subtask 1.2: Inspect the dataframe

Inspect the dataframe's columns, shapes, variable types etc.

In [4]:
# Write your code for inspection here
print(movies.columns)
print(movies.shape)
print(movies.values)
print(movies.head)
print(movies.tail)
print(movies.describe)

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')
(5043, 28)
[['Color' 'James Cameron' 723.0 ... 7.9 1.78 33000]
 ['Color' 'Gore Verbinski' 302.0 ... 7.1 2.35 0]
 ['Color' 'Sam Mendes' 602.0 ... 6.8 2.35 85000]
 ...
 ['Color' 'Benjamin Roberds' 13.0 ... 6.3 nan 16]
 ['Color' 'Daniel Hsia' 14.0 ... 6.3 2.35 660]
 ['Color' 'Jon Gunn' 43.0 ... 6.6 1.85 456]]
<bound method NDFrame.head of       color      director_name  num_critic_for_reviews  duration  \
0     Color      James Cameron                   723.0     178.0
1     Color     Gore Verbinski                   302.0     169.0
2     Color         Sam Mendes                   602.0     148.0
3     Color  Christopher Nolan                   813.0     164.0
4       NaN        Doug Walker                     NaN       NaN
...     ...                ...                     ...       ...
5038  Color        Scott Smith                     1.0      87.0
5039  Color                NaN                    43.0      43.0
5040  Color   Benjamin Roberds                    13.0      76.0
5041  Color        Daniel Hsia                    14.0     100.0
5042  Color           Jon Gunn                    43.0      90.0

      director_facebook_likes  actor_3_facebook_likes      actor_2_name  \
0                         0.0                   855.0  Joel David Moore
1                       563.0                  1000.0     Orlando Bloom
2                         0.0                   161.0      Rory Kinnear
3                     22000.0                 23000.0    Christian Bale
4                       131.0                     NaN        Rob Walker
...                       ...                     ...               ...
5038                      2.0                   318.0     Daphne Zuniga
5039                      NaN                   319.0     Valorie Curry
5040                      0.0                     0.0     Maxwell Moody
5041                      0.0                   489.0     Daniel Henney
5042                     16.0                    16.0  Brian Herzlinger

      actor_1_facebook_likes        gross                           genres  \
0                     1000.0  760505847.0  Action|Adventure|Fantasy|Sci-Fi
1                    40000.0  309404152.0         Action|Adventure|Fantasy
2                    11000.0  200074175.0        Action|Adventure|Thriller
3                    27000.0  448130642.0                  Action|Thriller
4                      131.0          NaN                      Documentary
...                      ...          ...                              ...
5038                   637.0          NaN                     Comedy|Drama
5039                   841.0          NaN     Crime|Drama|Mystery|Thriller
5040                     0.0          NaN            Drama|Horror|Thriller
5041                   946.0      10443.0             Comedy|Drama|Romance
5042                    86.0      85222.0                      Documentary

      ... num_user_for_reviews language  country  content_rating       budget  \
0     ...               3054.0  English      USA           PG-13  237000000.0
1     ...               1238.0  English      USA           PG-13  300000000.0
2     ...                994.0  English       UK           PG-13  245000000.0
3     ...               2701.0  English      USA           PG-13  250000000.0
4     ...                  NaN      NaN      NaN             NaN          NaN
...   ...                  ...      ...      ...             ...          ...
5038  ...                  6.0  English   Canada             NaN          NaN
5039  ...                359.0  English      USA           TV-14          NaN
5040  ...                  3.0  English      USA             NaN       1400.0
5041  ...                  9.0  English      USA           PG-13          NaN
5042  ...                 84.0  English      USA              PG       1100.0

      title_year actor_2_facebook_likes imdb_score  aspect_ratio  \
0         2009.0                  936.0        7.9          1.78
1         2007.0                 5000.0        7.1          2.35
2         2015.0                  393.0        6.8          2.35
3         2012.0                23000.0        8.5          2.35
4            NaN                   12.0        7.1           NaN
...          ...                    ...        ...           ...
5038      2013.0                  470.0        7.7           NaN
5039         NaN                  593.0        7.5         16.00
5040      2013.0                    0.0        6.3           NaN
5041      2012.0                  719.0        6.3          2.35
5042      2004.0                   23.0        6.6          1.85

     movie_facebook_likes
0                   33000
1                       0
2                   85000
3                  164000
4                       0
...                   ...
5038                   84
5039                32000
5040                   16
5041                  660
5042                  456

[5043 rows x 28 columns]>
<bound method NDFrame.tail of       color      director_name  num_critic_for_reviews  duration  \
0     Color      James Cameron                   723.0     178.0
1     Color     Gore Verbinski                   302.0     169.0
2     Color         Sam Mendes                   602.0     148.0
3     Color  Christopher Nolan                   813.0     164.0
4       NaN        Doug Walker                     NaN       NaN
...     ...                ...                     ...       ...
5038  Color        Scott Smith                     1.0      87.0
5039  Color                NaN                    43.0      43.0
5040  Color   Benjamin Roberds                    13.0      76.0
5041  Color        Daniel Hsia                    14.0     100.0
5042  Color           Jon Gunn                    43.0      90.0

      director_facebook_likes  actor_3_facebook_likes      actor_2_name  \
0                         0.0                   855.0  Joel David Moore
1                       563.0                  1000.0     Orlando Bloom
2                         0.0                   161.0      Rory Kinnear
3                     22000.0                 23000.0    Christian Bale
4                       131.0                     NaN        Rob Walker
...                       ...                     ...               ...
5038                      2.0                   318.0     Daphne Zuniga
5039                      NaN                   319.0     Valorie Curry
5040                      0.0                     0.0     Maxwell Moody
5041                      0.0                   489.0     Daniel Henney
5042                     16.0                    16.0  Brian Herzlinger

      actor_1_facebook_likes        gross                           genres  \
0                     1000.0  760505847.0  Action|Adventure|Fantasy|Sci-Fi
1                    40000.0  309404152.0         Action|Adventure|Fantasy
2                    11000.0  200074175.0        Action|Adventure|Thriller
3                    27000.0  448130642.0                  Action|Thriller
4                      131.0          NaN                      Documentary
...                      ...          ...                              ...
5038                   637.0          NaN                     Comedy|Drama
5039                   841.0          NaN     Crime|Drama|Mystery|Thriller
5040                     0.0          NaN            Drama|Horror|Thriller
5041                   946.0      10443.0             Comedy|Drama|Romance
5042                    86.0      85222.0                      Documentary

      ... num_user_for_reviews language  country  content_rating       budget  \
0     ...               3054.0  English      USA           PG-13  237000000.0
1     ...               1238.0  English      USA           PG-13  300000000.0
2     ...                994.0  English       UK           PG-13  245000000.0
3     ...               2701.0  English      USA           PG-13  250000000.0
4     ...                  NaN      NaN      NaN             NaN          NaN
...   ...                  ...      ...      ...             ...          ...
5038  ...                  6.0  English   Canada             NaN          NaN
5039  ...                359.0  English      USA           TV-14          NaN
5040  ...                  3.0  English      USA             NaN       1400.0
5041  ...                  9.0  English      USA           PG-13          NaN
5042  ...                 84.0  English      USA              PG       1100.0

      title_year actor_2_facebook_likes imdb_score  aspect_ratio  \
0         2009.0                  936.0        7.9          1.78
1         2007.0                 5000.0        7.1          2.35
2         2015.0                  393.0        6.8          2.35
3         2012.0                23000.0        8.5          2.35
4            NaN                   12.0        7.1           NaN
...          ...                    ...        ...           ...
5038      2013.0                  470.0        7.7           NaN
5039         NaN                  593.0        7.5         16.00
5040      2013.0                    0.0        6.3           NaN
5041      2012.0                  719.0        6.3          2.35
5042      2004.0                   23.0        6.6          1.85

     movie_facebook_likes
0                   33000
1                       0
2                   85000
3                  164000
4                       0
...                   ...
5038                   84
5039                32000
5040                   16
5041                  660
5042                  456

[5043 rows x 28 columns]>
<bound method NDFrame.describe of       color      director_name  num_critic_for_reviews  duration  \
0     Color      James Cameron                   723.0     178.0
1     Color     Gore Verbinski                   302.0     169.0
2     Color         Sam Mendes                   602.0     148.0
3     Color  Christopher Nolan                   813.0     164.0
4       NaN        Doug Walker                     NaN       NaN
...     ...                ...                     ...       ...
5038  Color        Scott Smith                     1.0      87.0
5039  Color                NaN                    43.0      43.0
5040  Color   Benjamin Roberds                    13.0      76.0
5041  Color        Daniel Hsia                    14.0     100.0
5042  Color           Jon Gunn                    43.0      90.0

      director_facebook_likes  actor_3_facebook_likes      actor_2_name  \
0                         0.0                   855.0  Joel David Moore
1                       563.0                  1000.0     Orlando Bloom
2                         0.0                   161.0      Rory Kinnear
3                     22000.0                 23000.0    Christian Bale
4                       131.0                     NaN        Rob Walker
...                       ...                     ...               ...
5038                      2.0                   318.0     Daphne Zuniga
5039                      NaN                   319.0     Valorie Curry
5040                      0.0                     0.0     Maxwell Moody
5041                      0.0                   489.0     Daniel Henney
5042                     16.0                    16.0  Brian Herzlinger

      actor_1_facebook_likes        gross                           genres  \
0                     1000.0  760505847.0  Action|Adventure|Fantasy|Sci-Fi
1                    40000.0  309404152.0         Action|Adventure|Fantasy
2                    11000.0  200074175.0        Action|Adventure|Thriller
3                    27000.0  448130642.0                  Action|Thriller
4                      131.0          NaN                      Documentary
...                      ...          ...                              ...
5038                   637.0          NaN                     Comedy|Drama
5039                   841.0          NaN     Crime|Drama|Mystery|Thriller
5040                     0.0          NaN            Drama|Horror|Thriller
5041                   946.0      10443.0             Comedy|Drama|Romance
5042                    86.0      85222.0                      Documentary

      ... num_user_for_reviews language  country  content_rating       budget  \
0     ...               3054.0  English      USA           PG-13  237000000.0
1     ...               1238.0  English      USA           PG-13  300000000.0
2     ...                994.0  English       UK           PG-13  245000000.0
3     ...               2701.0  English      USA           PG-13  250000000.0
4     ...                  NaN      NaN      NaN             NaN          NaN
...   ...                  ...      ...      ...             ...          ...
5038  ...                  6.0  English   Canada             NaN          NaN
5039  ...                359.0  English      USA           TV-14          NaN
5040  ...                  3.0  English      USA             NaN       1400.0
5041  ...                  9.0  English      USA           PG-13          NaN
5042  ...                 84.0  English      USA              PG       1100.0

      title_year actor_2_facebook_likes imdb_score  aspect_ratio  \
0         2009.0                  936.0        7.9          1.78
1         2007.0                 5000.0        7.1          2.35
2         2015.0                  393.0        6.8          2.35
3         2012.0                23000.0        8.5          2.35
4            NaN                   12.0        7.1           NaN
...          ...                    ...        ...           ...
5038      2013.0                  470.0        7.7           NaN
5039         NaN                  593.0        7.5         16.00
5040      2013.0                    0.0        6.3           NaN
5041      2012.0                  719.0        6.3          2.35
5042      2004.0                   23.0        6.6          1.85

     movie_facebook_likes
0                   33000
1                       0
2                   85000
3                  164000
4                       0
...                   ...
5038                   84
5039                32000
5040                   16
5041                  660
5042                  456

[5043 rows x 28 columns]>

## Task 2: Cleaning the Data

-  ### Subtask 2.1: Inspect Null values

Find out the number of Null values in all the columns and rows. Also, find the percentage of Null values in each column. Round off the percentages upto two decimal places.

In [5]:
# Write your code for column-wise null count here
print(movies.isnull().sum())

color                         19
director_name                104
num_critic_for_reviews        50
duration                      15
director_facebook_likes      104
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        884
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                153
movie_imdb_link                0
num_user_for_reviews          21
language                      12
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64

In [6]:
# Write your code for row-wise null count here
x=0
for x in range(1,5043):
   print(x,movies.loc[[x]].isna().sum().sum())

1 0
2 0
3 0
4 14
5 0
6 0
7 0
8 0
9 0
10 0
11 0
12 0
13 0
14 0
15 0
16 0
17 0
18 0
19 0
20 0
21 0
22 0
23 0
24 0
25 0
26 0
27 0
28 0
29 0
30 0
31 0
32 0
33 0
34 0
35 0
36 0
37 0
38 0
39 0
40 0
41 0
42 0
43 0
44 0
45 0
46 0
47 0
48 0
49 0
50 0
51 0
52 0
53 0
54 0
55 1
56 0
57 0
58 0
59 0
60 0
61 0
62 0
63 0
64 0
65 0
66 0
67 0
68 0
69 0
70 0
71 0
72 0
73 0
74 0
75 0
76 0
77 0
78 0
79 0
80 0
81 0
82 0
83 0
84 3
85 0
86 0
87 0
88 0
89 0
90 0
91 0
92 0
93 0
94 0
95 0
96 0
97 0
98 3
99 1
100 0
101 0
102 0
103 0
104 0
105 0
106 0
107 0
108 0
109 0
110 0
111 0
112 0
113 0
114 0
115 0
116 0
117 0
118 0
119 0
120 0
121 0
122 0
123 0
124 0
125 0
126 0
127 0
128 0
129 0
130 0
131 0
132 0
133 0
134 0
135 0
136 0
137 0
138 0
139 0
140 0
141 0
142 0
143 0
144 0
145 0
146 0
147 0
148 0
149 0
150 0
151 0
152 0
153 0
154 0
155 0
156 0
157 0
158 0
159 0
160 0
161 0
162 0
163 0
164 0
165 0
166 0
167 0
168 0
169 0
170 0
171 0
172 0
173 0
174 0
175 0
176 0
177 4
178 0
179 0
180 0
181 0
182 0
183 0
184 0
185 0
186 0
187 0
188 0
189 0
190 0
191 0
192 0
193 0
194 0
195 0
196 0
197 0
198 0
199 6
200 0
201 0
202 0
203 0
204 3
205 0
206 6
207 0
208 0
209 0
210 0
211 0
212 0
213 0
214 0
215 0
216 0
217 0
218 0
219 0
220 0
221 0
222 0
223 0
224 0
225 0
226 0
227 0
228 0
229 0
230 0
231 0
232 0
233 0
234 0
235 0
236 0
237 0
238 0
239 0
240 0
241 0
242 2
243 0
244 0
245 0
246 0
247 0
248 1
249 0
250 0
251 0
252 0
253 0
254 0
255 0
256 0
257 0
258 0
259 0
260 5
261 0
262 0
263 0
264 0
265 0
266 0
267 0
268 0
269 0
270 0
271 0
272 0
273 0
274 0
275 0
276 0
277 0
278 0
279 15
280 0
281 0
282 0
283 0
284 0
285 0
286 0
287 0
288 0
289 0
290 0
291 0
292 0
293 0
294 0
295 0
296 0
297 0
298 0
299 0
300 0
301 0
302 0
303 0
304 0
305 0
306 0
307 0
308 0
309 0
310 0
311 0
312 0
313 0
314 0
315 0
316 0
317 0
318 0
319 0
320 0
321 0
322 0
323 0
324 0
325 0
326 0
327 0
328 0
329 0
330 0
331 0
332 0
333 0
334 0
335 0
336 0
337 0
338 0
339 0
340 0
341 0
342 0
343 0
344 0
345 0
346 0
347 0
348 0
349 0
350 0
351 0
352 0
353 0
354 0
355 0
356 0
357 0
358 0
359 0
360 0
361 0
362 0
363 0
364 0
365 0
366 0
367 3
368 0
369 0
370 0
371 0
372 0
373 0
374 0
375 0
376 0
377 0
378 0
379 0
380 0
381 0
382 0
383 0
384 0
385 0
386 0
387 0
388 0
389 0
390 0
391 0
392 0
393 0
394 0
395 0
396 0
397 0
398 0
399 0
400 0
401 0
402 0
403 0
404 5
405 0
406 0
407 0
408 0
409 0
410 0
411 0
412 0
413 0
414 0
415 0
416 0
417 0
418 0
419 0
420 0
421 0
422 2
423 0
424 0
425 0
426 0
427 0
428 0
429 0
430 1
431 0
432 0
433 0
434 0
435 0
436 0
437 0
438 0
439 0
440 0
441 0
442 0
443 0
444 1
445 0
446 0
447 0
448 0
449 0
450 0
451 0
452 0
453 0
454 0
455 0
456 0
457 0
458 0
459 6
460 0
461 0
462 0
463 0
464 0
465 0
466 0
467 0
468 0
469 0
470 0
471 0
472 0
473 0
474 0
475 0
476 0
477 1
478 0
479 5
480 0
481 0
482 0
483 0
484 0
485 0
486 0
487 0
488 0
489 3
490 1
491 0
492 0
493 0
494 0
495 0
496 0
497 0
498 0
499 0
500 0
501 0
502 0
503 0
504 0
505 0
506 0
507 3
508 0
509 0
510 0
511 0
512 0
513 0
514 0
515 0
516 0
517 0
518 0
519 0
520 0
521 0
522 0
523 0
524 0
525 0
526 0
527 0
528 0
529 0
530 0
531 0
532 0
533 0
534 0
535 0
536 0
537 5
538 0
539 0
540 0
541 0
542 0
543 7
544 0
545 0
546 0
547 0
548 0
549 0
550 0
551 0
552 0
553 0
554 0
555 0
556 0
557 0
558 0
559 1
560 0
561 0
562 0
563 0
564 0
565 0
566 0
567 0
568 0
569 0
570 0
571 0
572 0
573 0
574 0
575 0
576 0
577 0
578 0
579 0
580 0
581 0
582 0
583 0
584 0
585 0
586 0
587 0
588 0
589 0
590 0
591 0
592 0
593 5
594 0
595 0
596 0
597 0
598 0
599 0
600 0
601 0
602 0
603 0
604 0
605 0
606 0
607 0
608 0
609 0
610 0
611 0
612 0
613 0
614 0
615 0
616 0
617 0
618 0
619 0
620 0
621 0
622 0
623 0
624 1
625 0
626 0
627 0
628 0
629 0
630 0
631 0
632 0
633 0
634 0
635 0
636 0
637 0
638 0
639 0
640 1
641 0
642 1
643 0
644 0
645 5
646 0
647 0
648 0
649 0
650 0
651 0
652 0
653 0
654 0
655 0
656 0
657 0
658 0
659 0
660 0
661 0
662 0
663 0
664 0
665 0
666 0
667 0
668 0
669 0
670 0
671 0
672 0
673 0
674 0
675 0
676 1
677 0
678 0
679 0
680 0
681 0
682 0
683 0
684 0
685 7
686 0
687 0
688 0
689 0
690 0
691 0
692 0
693 0
694 0
695 0
696 0
697 0
698 0
699 0
700 0
701 0
702 0
703 0
704 0
705 0
706 0
707 0
708 0
709 0
710 0
711 0
712 0
713 1
714 0
715 0
716 0
717 0
718 0
719 0
720 0
721 0
722 0
723 0
724 0
725 0
726 0
727 0
728 0
729 0
730 0
731 0
732 0
733 0
734 0
735 0
736 0
737 0
738 0
739 0
740 0
741 0
742 0
743 0
744 0
745 0
746 0
747 0
748 0
749 0
750 0
751 0
752 0
753 0
754 0
755 0
756 0
757 5
758 0
759 0
760 0
761 0
762 0
763 0
764 0
765 0
766 0
767 0
768 0
769 0
770 0
771 0
772 0
773 1
774 0
775 0
776 0
777 0
778 0
779 0
780 1
781 0
782 0
783 0
784 0
785 0
786 0
787 0
788 0
789 1
790 0
791 0
792 0
793 0
794 0
795 0
796 0
797 0
798 0
799 0
800 0
801 0
802 0
803 0
804 0
805 0
806 0
807 0
808 0
809 0
810 2
811 0
812 0
813 0
814 0
815 0
816 4
817 0
818 0
819 0
820 0
821 2
822 0
823 0
824 0
825 0
826 5
827 0
828 0
829 0
830 0
831 0
832 0
833 6
834 0
835 0
836 0
837 0
838 0
839 0
840 0
841 0
842 0
843 0
844 0
845 0
846 0
847 0
848 0
849 0
850 0
851 0
852 0
853 0
854 0
855 0
856 0
857 4
858 0
859 0
860 0
861 0
862 0
863 0
864 0
865 0
866 0
867 0
868 0
869 0
870 0
871 0
872 0
873 0
874 0
875 0
876 0
877 0
878 0
879 0
880 0
881 0
882 0
883 0
884 0
885 0
886 0
887 0
888 0
889 0
890 1
891 1
892 0
893 0
894 0
895 0
896 0
897 0
898 0
899 0
900 0
901 0
902 0
903 0
904 0
905 0
906 0
907 0
908 0
909 0
910 0
911 0
912 0
913 0
914 0
915 0
916 0
917 0
918 0
919 0
920 0
921 0
922 0
923 0
924 0
925 1
926 0
927 0
928 0
929 0
930 0
931 0
932 0
933 0
934 0
935 0
936 0
937 0
938 0
939 0
940 0
941 0
942 0
943 0
944 0
945 0
946 0
947 0
948 0
949 1
950 0
951 0
952 1
953 0
954 0
955 0
956 0
957 0
958 0
959 0
960 0
961 0
962 8
963 0
964 0
965 0
966 0
967 0
968 0
969 0
970 0
971 0
972 0
973 0
974 0
975 0
976 0
977 0
978 0
979 0
980 0
981 0
982 0
983 0
984 0
985 0
986 0
987 0
988 0
989 0
990 0
991 0
992 0
993 0
994 6
995 0
996 0
997 0
998 0
999 0
1000 0
1001 0
1002 0
1003 0
1004 0
1005 0
1006 0
1007 7
1008 0
1009 0
1010 0
1011 0
1012 0
1013 0
1014 0
1015 0
1016 0
1017 0
1018 0
1019 0
1020 0
1021 0
1022 0
1023 5
1024 0
1025 0
1026 0
1027 0
1028 0
1029 0
1030 0
1031 0
1032 0
1033 0
1034 0
1035 5
1036 0
1037 1
1038 0
1039 0
1040 1
1041 0
1042 0
1043 0
1044 2
1045 0
1046 0
1047 0
1048 0
1049 0
1050 0
1051 0
1052 0
1053 0
1054 0
1055 0
1056 2
1057 0
1058 0
1059 0
1060 1
1061 1
1062 0
1063 0
1064 0
1065 0
1066 0
1067 0
1068 0
1069 0
1070 0
1071 1
1072 1
1073 0
1074 0
1075 0
1076 0
1077 0
1078 0
1079 0
1080 0
1081 0
1082 0
1083 0
1084 0
1085 0
1086 0
1087 0
1088 0
1089 0
1090 0
1091 0
1092 0
1093 0
1094 0
1095 0
1096 0
1097 0
1098 0
1099 1
1100 0
1101 0
1102 0
1103 0
1104 0
1105 0
1106 0
1107 0
1108 0
1109 0
1110 0
1111 0
1112 0
1113 0
1114 0
1115 0
1116 0
1117 0
1118 0
1119 0
1120 0
1121 0
1122 0
1123 0
1124 0
1125 0
1126 0
1127 0
1128 0
1129 0
1130 0
1131 0
1132 0
1133 5
1134 0
1135 0
1136 2
1137 0
1138 0
1139 0
1140 0
1141 0
1142 0
1143 0
1144 0
1145 0
1146 0
1147 0
1148 0
1149 0
1150 0
1151 0
1152 0
1153 0
1154 0
1155 0
1156 0
1157 0
1158 0
1159 0
1160 0
1161 0
1162 0
1163 0
1164 0
1165 0
1166 0
1167 0
1168 0
1169 0
1170 0
1171 0
1172 0
1173 0
1174 0
1175 5
1176 0
1177 0
1178 4
1179 0
1180 0
1181 0
1182 0
1183 0
1184 0
1185 0
1186 0
1187 0
1188 0
1189 0
1190 0
1191 0
1192 0
1193 0
1194 0
1195 0
1196 0
1197 0
1198 0
1199 0
1200 0
1201 0
1202 0
1203 0
1204 0
1205 0
1206 0
1207 0
1208 0
1209 0
1210 0
1211 0
1212 0
1213 0
1214 0
1215 0
1216 0
1217 0
1218 0
1219 0
1220 0
1221 0
1222 0
1223 0
1224 0
1225 0
1226 1
1227 0
1228 0
1229 0
1230 0
1231 0
1232 0
1233 0
1234 0
1235 0
1236 0
1237 0
1238 0
1239 0
1240 0
1241 0
1242 0
1243 0
1244 0
1245 0
1246 0
1247 0
1248 0
1249 0
1250 0
1251 0
1252 0
1253 1
1254 0
1255 0
1256 0
1257 0
1258 0
1259 0
1260 0
1261 0
1262 0
1263 0
1264 0
1265 5
1266 0
1267 0
1268 0
1269 0
1270 0
1271 0
1272 0
1273 0
1274 0
1275 0
1276 0
1277 0
1278 0
1279 0
1280 0
1281 0
1282 0
1283 0
1284 0
1285 0
1286 0
1287 0
1288 0
1289 0
1290 0
1291 0
1292 0
1293 0
1294 0
1295 0
1296 0
1297 0
1298 0
1299 0
1300 0
1301 0
1302 0
1303 0
1304 0
1305 0
1306 0
1307 1
1308 0
1309 0
1310 0
1311 0
1312 0
1313 0
1314 0
1315 0
1316 0
1317 0
1318 0
1319 0
1320 0
1321 0
1322 0
1323 0
1324 0
1325 0
1326 1
1327 1
1328 0
1329 1
1330 0
1331 1
1332 0
1333 0
1334 0
1335 0
1336 0
1337 0
1338 0
1339 0
1340 0
1341 0
1342 0
1343 0
1344 0
1345 0
1346 5
1347 4
1348 0
1349 0
1350 0
1351 0
1352 0
1353 0
1354 0
1355 0
1356 0
1357 0
1358 0
1359 0
1360 0
1361 0
1362 0
1363 0

1364 0
1365 1
1366 0
1367 0
1368 0
1369 0
1370 0
1371 0
1372 0
1373 0
1374 0
1375 0
1376 0
1377 0
1378 0
1379 0
1380 0
1381 0
1382 3
1383 0
1384 0
1385 0
1386 0
1387 0
1388 0
1389 0
1390 0
1391 0
1392 0
1393 0
1394 0
1395 0
1396 0
1397 0
1398 0
1399 0
1400 0
1401 0
1402 0
1403 0
1404 6
1405 0
1406 0
1407 0
1408 0
1409 0
1410 0
1411 0
1412 0
1413 0
1414 0
1415 0
1416 0
1417 0
1418 0
1419 0
1420 0
1421 0
1422 0
1423 0
1424 0
1425 0
1426 0
1427 0
1428 0
1429 0
1430 0
1431 0
1432 0
1433 0
1434 0
1435 0
1436 0
1437 0
1438 0
1439 0
1440 0
1441 0
1442 0
1443 0
1444 7
1445 0
1446 2
1447 0
1448 0
1449 0
1450 0
1451 0
1452 0
1453 0
1454 0
1455 0
1456 0
1457 0
1458 0
1459 1
1460 0
1461 0
1462 0
1463 1
1464 0
1465 0
1466 0
1467 0
1468 0
1469 0
1470 0
1471 0
1472 0
1473 0
1474 0
1475 0
1476 0
1477 0
1478 0
1479 0
1480 0
1481 1
1482 1
1483 0
1484 0
1485 0
1486 0
1487 0
1488 0
1489 0
1490 0
1491 0
1492 0
1493 0
1494 0
1495 0
1496 0
1497 0
1498 0
1499 5
1500 0
1501 0
1502 0
1503 0
1504 1
1505 1
1506 0
1507 1
1508 3
1509 1
1510 6
1511 0
1512 0
1513 0
1514 0
1515 0
1516 0
1517 0
1518 0
1519 0
1520 0
1521 0
1522 0
1523 1
1524 0
1525 0
1526 0
1527 2
1528 0
1529 0
1530 0
1531 0
1532 0
1533 0
1534 0
1535 0
1536 0
1537 0
1538 0
1539 1
1540 0
1541 0
1542 0
1543 0
1544 0
1545 0
1546 0
1547 0
1548 0
1549 0
1550 0
1551 0
1552 0
1553 0
1554 0
1555 0
1556 1
1557 0
1558 0
1559 0
1560 0
1561 0
1562 0
1563 0
1564 0
1565 0
1566 0
1567 0
1568 0
1569 0
1570 1
1571 0
1572 0
1573 0
1574 0
1575 0
1576 0
1577 0
1578 0
1579 0
1580 0
1581 0
1582 0
1583 0
1584 0
1585 0
1586 0
1587 0
1588 0
1589 0
1590 0
1591 0
1592 0
1593 0
1594 0
1595 0
1596 0
1597 0
1598 0
1599 0
1600 0
1601 0
1602 0
1603 0
1604 0
1605 0
1606 0
1607 0
1608 0
1609 0
1610 0
1611 0
1612 0
1613 0
1614 0
1615 0
1616 0
1617 0
1618 0
1619 0
1620 5
1621 0
1622 0
1623 0
1624 0
1625 0
1626 0
1627 0
1628 0
1629 0
1630 0
1631 0
1632 0
1633 0
1634 0
1635 0
1636 0
1637 1
1638 0
1639 0
1640 0
1641 1
1642 0
1643 1
1644 0
1645 0
1646 0
1647 0
1648 0
1649 0
1650 0
1651 0
1652 0
1653 0
1654 0
1655 0
1656 0
1657 0
1658 0
1659 5
1660 0
1661 0
1662 0
1663 0
1664 5
1665 0
1666 0
1667 0
1668 0
1669 1
1670 0
1671 0
1672 0
1673 0
1674 0
1675 0
1676 0
1677 0
1678 0
1679 0
1680 0
1681 0
1682 0
1683 0
1684 0
1685 0
1686 0
1687 0
1688 0
1689 0
1690 0
1691 0
1692 0
1693 0
1694 0
1695 0
1696 0
1697 0
1698 0
1699 0
1700 0
1701 0
1702 0
1703 0
1704 0
1705 0
1706 0
1707 0
1708 0
1709 1
1710 6
1711 0
1712 0
1713 0
1714 0
1715 0
1716 0
1717 0
1718 1
1719 0
1720 0
1721 0
1722 0
1723 0
1724 3
1725 1
1726 0
1727 2
1728 1
1729 1
1730 2
1731 3
1732 1
1733 1
1734 0
1735 0
1736 5
1737 0
1738 0
1739 0
1740 1
1741 0
1742 0
1743 0
1744 0
1745 0
1746 0
1747 0
1748 0
1749 0
1750 0
1751 0
1752 1
1753 0
1754 0
1755 0
1756 0
1757 0
1758 0
1759 0
1760 0
1761 1
1762 0
1763 0
1764 0
1765 0
1766 0
1767 0
1768 0
1769 0
1770 0
1771 0
1772 0
1773 0
1774 0
1775 0
1776 0
1777 0
1778 0
1779 0
1780 0
1781 0
1782 2
1783 0
1784 0
1785 0
1786 0
1787 0
1788 0
1789 0
1790 0
1791 0
1792 0
1793 2
1794 0
1795 0
1796 0
1797 0
1798 0
1799 0
1800 0
1801 0
1802 5
1803 0
1804 0
1805 0
1806 0
1807 0
1808 1
1809 0
1810 0
1811 0
1812 0
1813 0
1814 0
1815 1
1816 0
1817 0
1818 6
1819 1
1820 0
1821 0
1822 0
1823 0
1824 0
1825 0
1826 0
1827 0
1828 0
1829 0
1830 0
1831 2
1832 0
1833 0
1834 0
1835 0
1836 0
1837 0
1838 0
1839 0
1840 0
1841 0
1842 5
1843 0
1844 0
1845 0
1846 0
1847 0
1848 0
1849 0
1850 0
1851 0
1852 0
1853 0
1854 0
1855 0
1856 0
1857 0
1858 0
1859 0
1860 1
1861 0
1862 1
1863 0
1864 0
1865 0
1866 0
1867 0
1868 0
1869 0
1870 0
1871 0
1872 0
1873 0
1874 0
1875 0
1876 0
1877 0
1878 2
1879 0
1880 3
1881 0
1882 0
1883 0
1884 0
1885 0
1886 0
1887 0
1888 0
1889 0
1890 0
1891 0
1892 0
1893 0
1894 1
1895 0
1896 0
1897 0
1898 0
1899 0
1900 0
1901 0
1902 0
1903 0
1904 0
1905 0
1906 0
1907 0
1908 0
1909 0
1910 0
1911 0
1912 0
1913 0
1914 0
1915 0
1916 0
1917 0
1918 1
1919 0
1920 0
1921 0
1922 0
1923 0
1924 0
1925 0
1926 0
1927 0
1928 0
1929 0
1930 0
1931 0
1932 0
1933 0
1934 0
1935 1
1936 0
1937 0
1938 0
1939 0
1940 0
1941 0
1942 1
1943 0
1944 0
1945 0
1946 0
1947 6
1948 2
1949 0
1950 0
1951 0
1952 0
1953 0
1954 0
1955 0
1956 0
1957 0
1958 1
1959 0
1960 0
1961 0
1962 0
1963 0
1964 0
1965 0
1966 0
1967 1
1968 0
1969 0
1970 0
1971 1
1972 5
1973 0
1974 0
1975 0
1976 0
1977 2
1978 0
1979 0
1980 0
1981 0
1982 0
1983 0
1984 0
1985 0
1986 0
1987 0
1988 0
1989 0
1990 1
1991 0
1992 0
1993 0
1994 0
1995 0
1996 0
1997 0
1998 0
1999 1
2000 0
2001 2
2002 0
2003 0
2004 0
2005 0
2006 2
2007 0
2008 0
2009 2
2010 2
2011 0
2012 1
2013 1
2014 1
2015 3
2016 0
2017 0
2018 0
2019 0
2020 0
2021 0
2022 0
2023 0
2024 0
2025 0
2026 0
2027 0
2028 0
2029 0
2030 0
2031 0
2032 0
2033 0
2034 0
2035 0
2036 0
2037 0
2038 0
2039 0
2040 0
2041 0
2042 0
2043 1
2044 0
2045 0
2046 0
2047 0
2048 0
2049 0
2050 0
2051 0
2052 0
2053 0
2054 0
2055 0
2056 0
2057 0
2058 0
2059 0
2060 0
2061 0
2062 0
2063 0
2064 0
2065 0
2066 0
2067 0
2068 0
2069 0
2070 0
2071 1
2072 0
2073 2
2074 0
2075 7
2076 0
2077 2
2078 0
2079 0
2080 0
2081 0
2082 0
2083 0
2084 0
2085 0
2086 0
2087 0
2088 1
2089 0
2090 0
2091 0
2092 0
2093 0
2094 0
2095 0
2096 0
2097 0
2098 0
2099 0
2100 1
2101 0
2102 0
2103 0
2104 0
2105 0
2106 0
2107 0
2108 0
2109 0
2110 0
2111 0
2112 0
2113 0
2114 0
2115 0
2116 0
2117 1
2118 0
2119 0
2120 0
2121 0
2122 0
2123 1
2124 0
2125 0
2126 0
2127 0
2128 0
2129 0
2130 1
2131 0
2132 0
2133 0
2134 0
2135 0
2136 0
2137 0
2138 0
2139 1
2140 0
2141 0
2142 0
2143 10
2144 0
2145 0
2146 0
2147 0
2148 0
2149 0
2150 0
2151 0
2152 0
2153 0
2154 0
2155 0
2156 0
2157 0
2158 0
2159 0
2160 0
2161 0
2162 0
2163 0
2164 0
2165 0
2166 0
2167 0
2168 0
2169 0
2170 0
2171 0
2172 0
2173 0
2174 0
2175 0
2176 0
2177 0
2178 0
2179 0
2180 1
2181 1
2182 0
2183 0
2184 0
2185 0
2186 0
2187 0
2188 0
2189 1
2190 0
2191 6
2192 0
2193 0
2194 0
2195 0
2196 0
2197 0
2198 0
2199 0
2200 1
2201 0
2202 0
2203 0
2204 0
2205 0
2206 0
2207 0
2208 0
2209 0
2210 0
2211 1
2212 0
2213 0
2214 0
2215 0
2216 0
2217 1
2218 0
2219 0
2220 0
2221 0
2222 0
2223 0
2224 0
2225 0
2226 0
2227 0
2228 0
2229 0
2230 0
2231 0
2232 0
2233 0
2234 0
2235 1
2236 0
2237 0
2238 1
2239 1
2240 0
2241 11
2242 0
2243 0
2244 0
2245 0
2246 0
2247 1
2248 0
2249 0
2250 0
2251 0
2252 0
2253 0
2254 0
2255 0
2256 0
2257 7
2258 0
2259 0
2260 0
2261 0
2262 0
2263 0
2264 0
2265 1
2266 0
2267 1
2268 0
2269 0
2270 0
2271 0
2272 0
2273 0
2274 0
2275 0
2276 0
2277 0
2278 0
2279 0
2280 0
2281 0
2282 0
2283 0
2284 0
2285 0
2286 0
2287 0
2288 0
2289 0
2290 0
2291 0
2292 0
2293 0
2294 0
2295 0
2296 0
2297 0
2298 0
2299 1
2300 0
2301 0
2302 0
2303 6
2304 0
2305 0
2306 0
2307 0
2308 0
2309 1
2310 0
2311 0
2312 0
2313 0
2314 0
2315 0
2316 0
2317 1
2318 0
2319 0
2320 0
2321 0
2322 0
2323 0
2324 0
2325 0
2326 0
2327 0
2328 0
2329 0
2330 0
2331 0
2332 1
2333 0
2334 0
2335 0
2336 1
2337 0
2338 1
2339 1
2340 0
2341 0
2342 10
2343 0
2344 1
2345 4
2346 1
2347 1
2348 1
2349 3
2350 2
2351 3
2352 1
2353 1
2354 0
2355 0
2356 0
2357 0
2358 0
2359 0
2360 0
2361 0
2362 1
2363 0
2364 0
2365 0
2366 4
2367 0
2368 0
2369 0
2370 8
2371 0
2372 0
2373 0
2374 3
2375 0
2376 0
2377 0
2378 0
2379 1
2380 0
2381 1
2382 0
2383 0
2384 1
2385 0
2386 0
2387 0
2388 3
2389 0
2390 0
2391 0
2392 0
2393 0
2394 0
2395 0
2396 0
2397 0
2398 0
2399 0
2400 0
2401 0
2402 0
2403 0
2404 0
2405 0
2406 0
2407 0
2408 0
2409 0
2410 0
2411 0
2412 5
2413 0
2414 0
2415 0
2416 0
2417 0
2418 0
2419 0
2420 0
2421 0
2422 1
2423 0
2424 0
2425 0
2426 0
2427 0
2428 0
2429 0
2430 0
2431 0
2432 0
2433 0
2434 0
2435 0
2436 0
2437 0
2438 0
2439 0
2440 1
2441 0
2442 0
2443 0
2444 0
2445 0
2446 0
2447 0
2448 0
2449 0
2450 0
2451 0
2452 0
2453 0
2454 0
2455 1
2456 0
2457 0
2458 0
2459 9
2460 0
2461 5
2462 0
2463 0
2464 1
2465 1
2466 4
2467 1
2468 0
2469 1
2470 2
2471 0
2472 2
2473 1
2474 1
2475 0
2476 1
2477 1
2478 0
2479 0
2480 0
2481 0
2482 0
2483 1
2484 0
2485 0
2486 0
2487 0
2488 0
2489 0
2490 0
2491 0
2492 0
2493 0
2494 0
2495 0
2496 0
2497 0
2498 0
2499 0
2500 0
2501 0
2502 0
2503 0
2504 0
2505 1
2506 1
2507 0
2508 0
2509 0
2510 0
2511 0
2512 0
2513 0
2514 1
2515 0
2516 0
2517 0
2518 0
2519 1
2520 0
2521 1
2522 0
2523 0
2524 0
2525 0
2526 1
2527 0
2528 2
2529 1
2530 0
2531 0
2532 0
2533 0
2534 0
2535 0
2536 0
2537 0
2538 0
2539 0
2540 0
2541 0
2542 0
2543 0
2544 0
2545 0
2546 0
2547 0
2548 0
2549 0
2550 0
2551 0
2552 7
2553 0
2554 0
2555 0
2556 0
2557 0
2558 0
2559 0
2560 0
2561 2
2562 1
2563 0
2564 0
2565 0
2566 0
2567 0
2568 0
2569 0
2570 0
2571 0
2572 0
2573 0
2574 1
2575 1
2576 0
2577 0
2578 0
2579 0

2580 0
2581 0
2582 0
2583 0
2584 0
2585 0
2586 2
2587 0
2588 0
2589 0
2590 1
2591 1
2592 0
2593 0
2594 4
2595 1
2596 1
2597 0
2598 0
2599 0
2600 0
2601 0
2602 0
2603 0
2604 0
2605 0
2606 0
2607 0
2608 0
2609 5
2610 0
2611 0
2612 2
2613 1
2614 0
2615 0
2616 1
2617 0
2618 0
2619 0
2620 0
2621 0
2622 0
2623 0
2624 0
2625 0
2626 0
2627 0
2628 0
2629 1
2630 0
2631 0
2632 0
2633 0
2634 0
2635 1
2636 0
2637 0
2638 0
2639 0
2640 0
2641 0
2642 0
2643 0
2644 0
2645 0
2646 0
2647 0
2648 0
2649 0
2650 0
2651 0
2652 0
2653 0
2654 0
2655 0
2656 0
2657 0
2658 0
2659 0
2660 0
2661 0
2662 0
2663 0
2664 0
2665 0
2666 0
2667 0
2668 0
2669 0
2670 0
2671 0
2672 0
2673 0
2674 0
2675 0
2676 0
2677 0
2678 0
2679 0
2680 0
2681 0
2682 0
2683 0
2684 0
2685 0
2686 1
2687 0
2688 0
2689 0
2690 0
2691 1
2692 0
2693 0
2694 0
2695 0
2696 0
2697 0
2698 0
2699 0
2700 0
2701 0
2702 6
2703 0
2704 0
2705 0
2706 0
2707 0
2708 0
2709 0
2710 3
2711 0
2712 0
2713 0
2714 0
2715 0
2716 0
2717 0
2718 0
2719 0
2720 0
2721 0
2722 0
2723 0
2724 1
2725 0
2726 0
2727 6
2728 0
2729 0
2730 0
2731 0
2732 3
2733 1
2734 0
2735 0
2736 0
2737 0
2738 0
2739 1
2740 0
2741 1
2742 1
2743 0
2744 2
2745 0
2746 0
2747 0
2748 2
2749 2
2750 1
2751 1
2752 4
2753 2
2754 2
2755 0
2756 0
2757 0
2758 0
2759 2
2760 0
2761 0
2762 0
2763 0
2764 0
2765 7
2766 0
2767 2
2768 0
2769 0
2770 0
2771 0
2772 1
2773 0
2774 0
2775 7
2776 0
2777 0
2778 1
2779 0
2780 0
2781 0
2782 0
2783 0
2784 0
2785 0
2786 1
2787 0
2788 0
2789 0
2790 0
2791 0
2792 0
2793 0
2794 1
2795 0
2796 1
2797 0
2798 0
2799 0
2800 0
2801 0
2802 1
2803 0
2804 0
2805 0
2806 0
2807 0
2808 0
2809 1
2810 0
2811 0
2812 1
2813 0
2814 1
2815 0
2816 0
2817 2
2818 0
2819 0
2820 0
2821 0
2822 0
2823 0
2824 4
2825 0
2826 0
2827 1
2828 8
2829 0
2830 0
2831 1
2832 0
2833 0
2834 0
2835 0
2836 0
2837 0
2838 0
2839 0
2840 0
2841 0
2842 0
2843 0
2844 0
2845 0
2846 0
2847 0
2848 0
2849 0
2850 0
2851 0
2852 0
2853 0
2854 0
2855 0
2856 0
2857 0
2858 0
2859 0
2860 0
2861 0
2862 0
2863 0
2864 0
2865 1
2866 0
2867 0
2868 0
2869 0
2870 8
2871 0
2872 0
2873 0
2874 0
2875 0
2876 0
2877 0
2878 0
2879 0
2880 0
2881 0
2882 0
2883 0
2884 0
2885 0
2886 0
2887 0
2888 0
2889 0
2890 0
2891 0
2892 3
2893 0
2894 0
2895 1
2896 0
2897 0
2898 0
2899 1
2900 0
2901 0
2902 1
2903 0
2904 2
2905 0
2906 0
2907 0
2908 0
2909 0
2910 0
2911 0
2912 0
2913 0
2914 0
2915 0
2916 0
2917 0
2918 0
2919 0
2920 0
2921 0
2922 0
2923 0
2924 0
2925 0
2926 0
2927 0
2928 0
2929 0
2930 0
2931 0
2932 0
2933 0
2934 0
2935 0
2936 0
2937 1
2938 0
2939 0
2940 0
2941 0
2942 0
2943 0
2944 0
2945 0
2946 0
2947 0
2948 0
2949 0
2950 1
2951 0
2952 5
2953 0
2954 0
2955 1
2956 0
2957 0
2958 1
2959 0
2960 0
2961 0
2962 0
2963 0
2964 1
2965 0
2966 1
2967 1
2968 1
2969 1
2970 0
2971 0
2972 0
2973 0
2974 0
2975 0
2976 0
2977 0
2978 0
2979 0
2980 0
2981 0
2982 0
2983 0
2984 0
2985 0
2986 0
2987 0
2988 0
2989 1
2990 0
2991 0
2992 0
2993 0
2994 0
2995 0
2996 0
2997 0
2998 0
2999 0
3000 0
3001 0
3002 0
3003 1
3004 0
3005 0
3006 0
3007 1
3008 1
3009 0
3010 0
3011 3
3012 1
3013 0
3014 1
3015 1
3016 1
3017 0
3018 3
3019 0
3020 1
3021 1
3022 3
3023 0
3024 0
3025 0
3026 0
3027 1
3028 0
3029 0
3030 1
3031 0
3032 0
3033 3
3034 0
3035 1
3036 0
3037 0
3038 0
3039 0
3040 0
3041 1
3042 0
3043 0
3044 0
3045 1
3046 0
3047 0
3048 1
3049 0
3050 0
3051 0
3052 0
3053 0
3054 0
3055 0
3056 0
3057 0
3058 0
3059 0
3060 0
3061 0
3062 0
3063 0
3064 0
3065 0
3066 1
3067 1
3068 0
3069 0
3070 1
3071 0
3072 2
3073 1
3074 0
3075 0
3076 0
3077 0
3078 0
3079 0
3080 0
3081 0
3082 1
3083 1
3084 7
3085 3
3086 1
3087 0
3088 2
3089 0
3090 1
3091 0
3092 0
3093 0
3094 0
3095 0
3096 0
3097 0
3098 0
3099 0
3100 0
3101 1
3102 0
3103 0
3104 0
3105 0
3106 0
3107 0
3108 0
3109 0
3110 0
3111 1
3112 0
3113 0
3114 0
3115 0
3116 0
3117 0
3118 0
3119 0
3120 0
3121 0
3122 0
3123 0
3124 0
3125 0
3126 0
3127 0
3128 0
3129 2
3130 1
3131 0
3132 0
3133 0
3134 0
3135 0
3136 0
3137 1
3138 1
3139 0
3140 0
3141 0
3142 0
3143 0
3144 0
3145 0
3146 0
3147 0
3148 1
3149 0
3150 0
3151 0
3152 0
3153 1
3154 0
3155 0
3156 0
3157 0
3158 0
3159 0
3160 0
3161 0
3162 0
3163 0
3164 0
3165 0
3166 1
3167 0
3168 0
3169 0
3170 0
3171 0
3172 0
3173 1
3174 5
3175 0
3176 0
3177 0
3178 0
3179 0
3180 0
3181 0
3182 1
3183 1
3184 0
3185 0
3186 0
3187 1
3188 0
3189 0
3190 0
3191 0
3192 0
3193 0
3194 0
3195 0
3196 0
3197 0
3198 0
3199 0
3200 0
3201 0
3202 0
3203 0
3204 0
3205 0
3206 0
3207 4
3208 1
3209 0
3210 0
3211 0
3212 0
3213 0
3214 0
3215 1
3216 0
3217 0
3218 0
3219 0
3220 1
3221 0
3222 2
3223 1
3224 0
3225 0
3226 1
3227 0
3228 0
3229 1
3230 0
3231 1
3232 2
3233 1
3234 0
3235 0
3236 0
3237 0
3238 2
3239 1
3240 2
3241 0
3242 0
3243 2
3244 0
3245 1
3246 2
3247 1
3248 4
3249 1
3250 1
3251 1
3252 1
3253 1
3254 3
3255 0
3256 1
3257 2
3258 1
3259 0
3260 0
3261 2
3262 0
3263 2
3264 0
3265 0
3266 1
3267 0
3268 1
3269 1
3270 2
3271 0
3272 2
3273 2
3274 0
3275 1
3276 0
3277 0
3278 0
3279 0
3280 0
3281 0
3282 1
3283 3
3284 0
3285 0
3286 0
3287 0
3288 0
3289 0
3290 0
3291 0
3292 0
3293 1
3294 0
3295 1
3296 0
3297 1
3298 1
3299 0
3300 0
3301 0
3302 1
3303 5
3304 1
3305 0
3306 0
3307 0
3308 1
3309 1
3310 0
3311 0
3312 0
3313 4
3314 0
3315 0
3316 0
3317 1
3318 0
3319 0
3320 2
3321 1
3322 1
3323 0
3324 2
3325 1
3326 1
3327 1
3328 0
3329 5
3330 0
3331 1
3332 0
3333 0
3334 0
3335 1
3336 1
3337 0
3338 1
3339 0
3340 0
3341 1
3342 2
3343 0
3344 0
3345 0
3346 4
3347 0
3348 3
3349 1
3350 2
3351 0
3352 1
3353 0
3354 2
3355 0
3356 1
3357 0
3358 0
3359 0
3360 0
3361 0
3362 0
3363 0
3364 0
3365 0
3366 0
3367 0
3368 0
3369 0
3370 1
3371 0
3372 1
3373 5
3374 0
3375 0
3376 5
3377 0
3378 0
3379 1
3380 0
3381 0
3382 0
3383 0
3384 0
3385 1
3386 0
3387 1
3388 0
3389 0
3390 1
3391 0
3392 0
3393 1
3394 0
3395 0
3396 1
3397 6
3398 0
3399 0
3400 0
3401 0
3402 0
3403 0
3404 0
3405 0
3406 0
3407 1
3408 0
3409 0
3410 0
3411 0
3412 3
3413 0
3414 1
3415 0
3416 0
3417 0
3418 0
3419 7
3420 0
3421 0
3422 1
3423 0
3424 1
3425 1
3426 2
3427 3
3428 0
3429 2
3430 1
3431 2
3432 0
3433 2
3434 0
3435 0
3436 0
3437 2
3438 0
3439 0
3440 0
3441 1
3442 0
3443 0
3444 0
3445 0
3446 1
3447 0
3448 1
3449 2
3450 0
3451 4
3452 0
3453 0
3454 3
3455 2
3456 0
3457 1
3458 2
3459 0
3460 0
3461 0
3462 0
3463 0
3464 1
3465 0
3466 0
3467 0
3468 0
3469 0
3470 0
3471 0
3472 0
3473 0
3474 1
3475 0
3476 0
3477 0
3478 0
3479 0
3480 0
3481 5
3482 0
3483 0
3484 0
3485 0
3486 2
3487 0
3488 0
3489 0
3490 4
3491 0
3492 0
3493 0
3494 0
3495 2
3496 0
3497 0
3498 0
3499 1
3500 0
3501 0
3502 0
3503 0
3504 0
3505 0
3506 0
3507 6
3508 0
3509 5
3510 1
3511 0
3512 0
3513 0
3514 0
3515 0
3516 0
3517 2
3518 0
3519 2
3520 0
3521 0
3522 0
3523 0
3524 1
3525 0
3526 0
3527 1
3528 2
3529 0
3530 0
3531 0
3532 1
3533 0
3534 0
3535 1
3536 3
3537 1
3538 2
3539 5
3540 0
3541 3
3542 0
3543 1
3544 3
3545 2
3546 1
3547 0
3548 0
3549 0
3550 0
3551 0
3552 1
3553 0
3554 0
3555 0
3556 0
3557 0
3558 2
3559 0
3560 0
3561 0
3562 0
3563 1
3564 0
3565 0
3566 0
3567 0
3568 0
3569 0
3570 0
3571 1
3572 0
3573 1
3574 0
3575 0
3576 0
3577 0
3578 1
3579 6
3580 0
3581 0
3582 0
3583 0
3584 0
3585 0
3586 0
3587 0
3588 0
3589 0
3590 0
3591 0
3592 0
3593 0
3594 0
3595 0
3596 0
3597 0
3598 0
3599 0
3600 0
3601 1
3602 1
3603 0
3604 6
3605 0
3606 0
3607 0
3608 0
3609 0
3610 3
3611 0
3612 0
3613 0
3614 0
3615 0
3616 0
3617 0
3618 0
3619 1
3620 0
3621 0
3622 0
3623 5
3624 0
3625 0
3626 3
3627 0
3628 0
3629 1
3630 1
3631 0
3632 1
3633 1
3634 0
3635 0
3636 1
3637 0
3638 1
3639 0
3640 0
3641 1
3642 0
3643 2
3644 1
3645 1
3646 2
3647 0
3648 1
3649 1
3650 6
3651 1
3652 0
3653 1
3654 0
3655 0
3656 3
3657 1
3658 1
3659 0
3660 1
3661 5
3662 0
3663 0
3664 0
3665 2
3666 0
3667 2
3668 0
3669 0
3670 0
3671 0
3672 0
3673 1
3674 0
3675 0
3676 2
3677 0
3678 0
3679 0
3680 0
3681 0
3682 0
3683 1
3684 0
3685 1
3686 3
3687 0
3688 0
3689 1
3690 0
3691 1
3692 0
3693 2
3694 1
3695 2
3696 0
3697 0
3698 0
3699 0
3700 0
3701 0
3702 0
3703 0
3704 0
3705 0
3706 0
3707 0
3708 1
3709 0
3710 0
3711 1
3712 0
3713 1
3714 0
3715 0
3716 0
3717 0
3718 0
3719 0
3720 0
3721 0
3722 1
3723 0
3724 0
3725 1
3726 0
3727 1
3728 0
3729 0
3730 0
3731 0
3732 0
3733 0
3734 1
3735 1
3736 0
3737 0
3738 0
3739 0
3740 0
3741 0
3742 0
3743 0
3744 0
3745 0
3746 0
3747 0
3748 0
3749 0
3750 0
3751 1
3752 2
3753 1
3754 0
3755 1
3756 2
3757 0
3758 0
3759 0
3760 1
3761 0
3762 1
3763 0
3764 1
3765 0
3766 1
3767 0
3768 0
3769 1
3770 1
3771 0
3772 0
3773 0
3774 2
3775 0
3776 0
3777 0
3778 0
3779 0
3780 0
3781 0
3782 0
3783 0
3784 0
3785 1
3786 1
3787 0
3788 0
3789 2

3790 1
3791 1
3792 1
3793 0
3794 1
3795 0
3796 1
3797 1
3798 0
3799 0
3800 5
3801 2
3802 1
3803 1
3804 1
3805 2
3806 5
3807 5
3808 1
3809 2
3810 4
3811 2
3812 1
3813 2
3814 1
3815 5
3816 6
3817 2
3818 4
3819 0
3820 1
3821 0
3822 1
3823 0
3824 0
3825 0
3826 0
3827 1
3828 2
3829 0
3830 1
3831 0
3832 4
3833 2
3834 6
3835 1
3836 1
3837 0
3838 4
3839 0
3840 2
3841 0
3842 1
3843 0
3844 1
3845 1
3846 0
3847 7
3848 0
3849 0
3850 2
3851 0
3852 1
3853 1
3854 0
3855 1
3856 0
3857 0
3858 1
3859 0
3860 2
3861 0
3862 0
3863 1
3864 1
3865 0
3866 5
3867 0
3868 1
3869 2
3870 2
3871 5
3872 2
3873 0
3874 1
3875 1
3876 0
3877 1
3878 2
3879 0
3880 1
3881 6
3882 1
3883 0
3884 0
3885 0
3886 0
3887 1
3888 0
3889 0
3890 0
3891 0
3892 0
3893 0
3894 0
3895 2
3896 1
3897 1
3898 0
3899 1
3900 5
3901 0
3902 0
3903 1
3904 1
3905 0
3906 0
3907 0
3908 0
3909 0
3910 0
3911 0
3912 1
3913 0
3914 1
3915 0
3916 0
3917 0
3918 0
3919 1
3920 1
3921 0
3922 0
3923 0
3924 0
3925 0
3926 0
3927 0
3928 0
3929 1
3930 0
3931 0
3932 0
3933 1
3934 1
3935 0
3936 0
3937 2
3938 0
3939 0
3940 0
3941 0
3942 0
3943 1
3944 0
3945 0
3946 1
3947 0
3948 1
3949 0
3950 0
3951 5
3952 0
3953 0
3954 1
3955 1
3956 2
3957 3
3958 1
3959 1
3960 1
3961 2
3962 1
3963 2
3964 2
3965 2
3966 2
3967 1
3968 1
3969 1
3970 0
3971 0
3972 0
3973 2
3974 0
3975 1
3976 1
3977 0
3978 0
3979 0
3980 0
3981 0
3982 5
3983 1
3984 0
3985 0
3986 1
3987 0
3988 0
3989 5
3990 0
3991 1
3992 1
3993 1
3994 1
3995 1
3996 0
3997 0
3998 0
3999 0
4000 0
4001 1
4002 2
4003 0
4004 0
4005 1
4006 0
4007 0
4008 0
4009 0
4010 0
4011 0
4012 1
4013 2
4014 1
4015 7
4016 2
4017 2
4018 3
4019 1
4020 1
4021 3
4022 1
4023 1
4024 0
4025 0
4026 2
4027 0
4028 0
4029 0
4030 0
4031 2
4032 1
4033 0
4034 1
4035 0
4036 1
4037 2
4038 1
4039 1
4040 1
4041 1
4042 1
4043 0
4044 0
4045 1
4046 0
4047 0
4048 1
4049 1
4050 0
4051 0
4052 0
4053 0
4054 0
4055 1
4056 0
4057 0
4058 0
4059 0
4060 0
4061 1
4062 1
4063 0
4064 1
4065 0
4066 0
4067 0
4068 1
4069 1
4070 0
4071 1
4072 0
4073 1
4074 2
4075 0
4076 1
4077 1
4078 1
4079 5
4080 1
4081 0
4082 0
4083 0
4084 0
4085 2
4086 0
4087 7
4088 1
4089 0
4090 0
4091 0
4092 1
4093 1
4094 0
4095 0
4096 1
4097 0
4098 0
4099 0
4100 1
4101 0
4102 1
4103 0
4104 0
4105 0
4106 0
4107 0
4108 2
4109 1
4110 2
4111 1
4112 1
4113 6
4114 0
4115 6
4116 3
4117 0
4118 0
4119 6
4120 0
4121 2
4122 0
4123 0
4124 0
4125 1
4126 2
4127 1
4128 0
4129 2
4130 1
4131 2
4132 2
4133 1
4134 1
4135 1
4136 3
4137 2
4138 3
4139 2
4140 2
4141 0
4142 1
4143 2
4144 0
4145 1
4146 3
4147 0
4148 3
4149 1
4150 1
4151 0
4152 2
4153 1
4154 0
4155 0
4156 0
4157 0
4158 0
4159 0
4160 1
4161 0
4162 1
4163 4
4164 2
4165 1
4166 2
4167 1
4168 0
4169 0
4170 1
4171 0
4172 1
4173 0
4174 2
4175 0
4176 2
4177 1
4178 1
4179 3
4180 0
4181 0
4182 0
4183 0
4184 0
4185 1
4186 1
4187 0
4188 0
4189 0
4190 0
4191 2
4192 0
4193 1
4194 1
4195 0
4196 0
4197 0
4198 2
4199 0
4200 0
4201 2
4202 0
4203 0
4204 0
4205 0
4206 0
4207 0
4208 0
4209 2
4210 1
4211 4
4212 0
4213 0
4214 1
4215 4
4216 0
4217 1
4218 1
4219 0
4220 1
4221 1
4222 1
4223 3
4224 2
4225 2
4226 1
4227 4
4228 0
4229 0
4230 0
4231 1
4232 2
4233 1
4234 3
4235 2
4236 3
4237 1
4238 0
4239 1
4240 0
4241 1
4242 1
4243 3
4244 3
4245 4
4246 3
4247 0
4248 0
4249 6
4250 1
4251 0
4252 1
4253 1
4254 0
4255 0
4256 1
4257 0
4258 0
4259 0
4260 0
4261 1
4262 1
4263 0
4264 0
4265 1
4266 0
4267 0
4268 0
4269 1
4270 0
4271 1
4272 1
4273 0
4274 1
4275 0
4276 1
4277 0
4278 0
4279 0
4280 0
4281 5
4282 0
4283 0
4284 0
4285 0
4286 1
4287 0
4288 6
4289 0
4290 1
4291 0
4292 1
4293 2
4294 0
4295 1
4296 0
4297 1
4298 0
4299 5
4300 1
4301 0
4302 2
4303 0
4304 5
4305 1
4306 2
4307 2
4308 1
4309 1
4310 1
4311 0
4312 0
4313 0
4314 3
4315 1
4316 1
4317 2
4318 0
4319 1
4320 1
4321 2
4322 1
4323 6
4324 1
4325 3
4326 1
4327 6
4328 0
4329 1
4330 1
4331 2
4332 2
4333 0
4334 2
4335 2
4336 2
4337 1
4338 3
4339 2
4340 2
4341 4
4342 2
4343 0
4344 0
4345 1
4346 0
4347 1
4348 2
4349 0
4350 0
4351 3
4352 0
4353 0
4354 5
4355 0
4356 0
4357 1
4358 1
4359 1
4360 0
4361 0
4362 1
4363 0
4364 1
4365 4
4366 1
4367 1
4368 1
4369 1
4370 3
4371 1
4372 7
4373 2
4374 1
4375 0
4376 0
4377 2
4378 1
4379 1
4380 1
4381 0
4382 0
4383 0
4384 0
4385 0
4386 0
4387 1
4388 1
4389 1
4390 2
4391 1
4392 2
4393 0
4394 2
4395 1
4396 1
4397 4
4398 0
4399 0
4400 3
4401 0
4402 0
4403 0
4404 1
4405 1
4406 0
4407 0
4408 1
4409 6
4410 1
4411 0
4412 0
4413 0
4414 1
4415 0
4416 1
4417 0
4418 0
4419 0
4420 0
4421 1
4422 2
4423 0
4424 0
4425 3
4426 1
4427 0
4428 0
4429 0
4430 1
4431 2
4432 1
4433 1
4434 0
4435 0
4436 6
4437 0
4438 1
4439 1
4440 3
4441 3
4442 2
4443 4
4444 3
4445 3
4446 0
4447 2
4448 3
4449 0
4450 0
4451 1
4452 0
4453 3
4454 2
4455 1
4456 2
4457 1
4458 0
4459 5
4460 8
4461 0
4462 0
4463 0
4464 0
4465 1
4466 0
4467 5
4468 1
4469 1
4470 0
4471 1
4472 1
4473 2
4474 1
4475 0
4476 1
4477 1
4478 1
4479 1
4480 1
4481 1
4482 6
4483 2
4484 0
4485 0
4486 0
4487 2
4488 2
4489 0
4490 0
4491 0
4492 1
4493 0
4494 0
4495 0
4496 0
4497 2
4498 0
4499 0
4500 0
4501 0
4502 7
4503 2
4504 2
4505 3
4506 2
4507 2
4508 1
4509 3
4510 2
4511 0
4512 1
4513 2
4514 3
4515 0
4516 1
4517 7
4518 0
4519 8
4520 1
4521 1
4522 0
4523 0
4524 1
4525 2
4526 1
4527 1
4528 4
4529 1
4530 0
4531 1
4532 0
4533 1
4534 0
4535 1
4536 0
4537 0
4538 0
4539 0
4540 0
4541 0
4542 0
4543 0
4544 0
4545 0
4546 0
4547 2
4548 3
4549 1
4550 1
4551 0
4552 2
4553 0
4554 1
4555 2
4556 0
4557 0
4558 1
4559 1
4560 1
4561 0
4562 0
4563 0
4564 0
4565 0
4566 0
4567 0
4568 1
4569 0
4570 0
4571 0
4572 1
4573 1
4574 0
4575 0
4576 0
4577 0
4578 1
4579 1
4580 2
4581 0
4582 1
4583 0
4584 0
4585 0
4586 0
4587 0
4588 3
4589 2
4590 0
4591 1
4592 0
4593 2
4594 0
4595 0
4596 0
4597 2
4598 1
4599 0
4600 2
4601 0
4602 0
4603 0
4604 2
4605 1
4606 0
4607 0
4608 1
4609 4
4610 1
4611 2
4612 2
4613 1
4614 3
4615 3
4616 2
4617 5
4618 1
4619 1
4620 2
4621 2
4622 4
4623 1
4624 2
4625 1
4626 3
4627 4
4628 1
4629 1
4630 5
4631 0
4632 2
4633 2
4634 8
4635 2
4636 3
4637 3
4638 0
4639 0
4640 0
4641 3
4642 0
4643 0
4644 1
4645 0
4646 0
4647 1
4648 1
4649 0
4650 0
4651 2
4652 2
4653 0
4654 1
4655 0
4656 1
4657 3
4658 4
4659 0
4660 4
4661 0
4662 0
4663 0
4664 1
4665 2
4666 2
4667 0
4668 2
4669 2
4670 2
4671 0
4672 1
4673 4
4674 0
4675 2
4676 0
4677 0
4678 1
4679 0
4680 0
4681 0
4682 1
4683 0
4684 0
4685 1
4686 1
4687 1
4688 0
4689 1
4690 5
4691 0
4692 2
4693 3
4694 0
4695 0
4696 0
4697 1
4698 1
4699 2
4700 1
4701 3
4702 3
4703 1
4704 3
4705 3
4706 0
4707 0
4708 0
4709 1
4710 0
4711 2
4712 0
4713 5
4714 4
4715 3
4716 3
4717 4
4718 4
4719 0
4720 8
4721 2
4722 3
4723 0
4724 2
4725 0
4726 0
4727 4
4728 0
4729 1
4730 0
4731 0
4732 1
4733 0
4734 1
4735 0
4736 0
4737 0
4738 1
4739 0
4740 0
4741 0
4742 0
4743 0
4744 0
4745 1
4746 2
4747 0
4748 1
4749 1
4750 0
4751 0
4752 0
4753 0
4754 0
4755 0
4756 2
4757 1
4758 0
4759 2
4760 2
4761 1
4762 1
4763 4
4764 3
4765 2
4766 1
4767 7
4768 3
4769 0
4770 2
4771 2
4772 2
4773 2
4774 4
4775 3
4776 2
4777 3
4778 0
4779 1
4780 0
4781 0
4782 2
4783 0
4784 0
4785 3
4786 0
4787 3
4788 0
4789 1
4790 3
4791 0
4792 0
4793 0
4794 1
4795 0
4796 0
4797 1
4798 5
4799 0
4800 1
4801 3
4802 0
4803 5
4804 0
4805 1
4806 1
4807 2
4808 1
4809 1
4810 2
4811 1
4812 0
4813 1
4814 0
4815 6
4816 0
4817 0
4818 2
4819 5
4820 2
4821 0
4822 1
4823 2
4824 1
4825 1
4826 1
4827 0
4828 0
4829 0
4830 0
4831 3
4832 0
4833 0
4834 2
4835 1
4836 5
4837 7
4838 1
4839 1
4840 0
4841 2
4842 0
4843 4
4844 1
4845 0
4846 4
4847 2
4848 1
4849 1
4850 2
4851 0
4852 0
4853 0
4854 3
4855 0
4856 0
4857 0
4858 0
4859 6
4860 0
4861 1
4862 0
4863 0
4864 0
4865 3
4866 1
4867 2
4868 0
4869 5
4870 3
4871 1
4872 2
4873 1
4874 2
4875 2
4876 3
4877 2
4878 6
4879 2
4880 3
4881 2
4882 3
4883 3
4884 3
4885 2
4886 3
4887 3
4888 1
4889 3
4890 0
4891 0
4892 1
4893 0
4894 1
4895 1
4896 0
4897 0
4898 1
4899 1
4900 1
4901 1
4902 1
4903 2
4904 1
4905 0
4906 1
4907 3
4908 1
4909 1
4910 5
4911 3
4912 2
4913 1
4914 1
4915 0
4916 2
4917 1
4918 4
4919 5
4920 3
4921 0
4922 0
4923 0
4924 5
4925 4
4926 0
4927 3
4928 0
4929 5
4930 0
4931 0
4932 2
4933 0
4934 3
4935 3
4936 0
4937 1
4938 3
4939 3
4940 3
4941 0
4942 1
4943 2
4944 1
4945 11
4946 8
4947 1
4948 8
4949 2
4950 2
4951 1
4952 2
4953 2
4954 3
4955 0
4956 0
4957 1
4958 2
4959 0
4960 1
4961 1
4962 0
4963 2
4964 0
4965 1
4966 1
4967 2
4968 2
4969 3
4970 1
4971 0
4972 3
4973 0
4974 2
4975 0
4976 4
4977 0
4978 0
4979 0
4980 1
4981 1
4982 3
4983 1
4984 0
4985 3
4986 2
4987 0
4988 2
4989 6

4990 8
4991 2
4992 7
4993 1
4994 3
4995 1
4996 3
4997 0
4998 0
4999 4
5000 1
5001 1
5002 3
5003 2
5004 1
5005 2
5006 3
5007 2
5008 0
5009 2
5010 3
5011 0
5012 0
5013 2
5014 2
5015 0
5016 5
5017 2
5018 2
5019 2
5020 5
5021 1
5022 4
5023 2
5024 1
5025 0
5026 0
5027 0
5028 3
5029 1
5030 5
5031 3
5032 4
5033 0
5034 1
5035 0
5036 3
5037 1
5038 4
5039 5
5040 4
5041 2
5042 0

In [7]:
# Write your code for column-wise null percentages here
round(movies.isnull().sum() * 100 / len(movies.index),2)

color                         0.38
director_name                 2.06
num_critic_for_reviews        0.99
duration                      0.30
director_facebook_likes       2.06
actor_3_facebook_likes        0.46
actor_2_name                  0.26
actor_1_facebook_likes        0.14
gross                        17.53
genres                        0.00
actor_1_name                  0.14
movie_title                   0.00
num_voted_users               0.00
cast_total_facebook_likes     0.00
actor_3_name                  0.46
facenumber_in_poster          0.26
plot_keywords                 3.03
movie_imdb_link               0.00
num_user_for_reviews          0.42
language                      0.24
country                       0.10
content_rating                6.01
budget                        9.76
title_year                    2.14
actor_2_facebook_likes        0.26
imdb_score                    0.00
aspect_ratio                  6.52
movie_facebook_likes          0.00
dtype: float64

-  ### Subtask 2.2: Drop unecessary columns

For this assignment, you will mostly be analyzing the movies with respect to the ratings, gross collection, popularity of movies, etc. So many of the columns in this dataframe are not required. So it is advised to drop the following columns.
-  color
-  director_facebook_likes
-  actor_1_facebook_likes
-  actor_2_facebook_likes
-  actor_3_facebook_likes
-  actor_2_name
-  cast_total_facebook_likes
-  actor_3_name
-  duration
-  facenumber_in_poster
-  content_rating
-  country
-  movie_imdb_link
-  aspect_ratio
-  plot_keywords

In [8]:
# Write your code for dropping the columns here. It is advised to keep inspecting the dataframe after each set of operations 
movies = movies.drop(['color','director_facebook_likes','actor_1_facebook_likes','actor_2_facebook_likes','actor_3_facebook_likes','actor_2_name','cast_total_facebook_likes','actor_3_name','duration','facenumber_in_poster','content_rating','country','movie_imdb_link','aspect_ratio','plot_keywords'],axis=1)
movies

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000
4,Doug Walker,NaN,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens ...,8,NaN,NaN,NaN,NaN,7.1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Scott Smith,1.0,NaN,Comedy|Drama,Eric Mabius,Signed Sealed Delivered,629,6.0,English,NaN,2013.0,7.7,84
5039,NaN,43.0,NaN,Crime|Drama|Mystery|Thriller,Natalie Zea,The Following,73839,359.0,English,NaN,NaN,7.5,32000
5040,Benjamin Roberds,13.0,NaN,Drama|Horror|Thriller,Eva Boehnke,A Plague So Pleasant,38,3.0,English,1400.0,2013.0,6.3,16
5041,Daniel Hsia,14.0,10443.0,Comedy|Drama|Romance,Alan Ruck,Shanghai Calling,1255,9.0,English,NaN,2012.0,6.3,660
5042,Jon Gunn,43.0,85222.0,Documentary,John August,My Date with Drew,4285,84.0,English,1100.0,2004.0,6.6,456

-  ### Subtask 2.3: Drop unecessary rows using columns with high Null percentages

Now, on inspection you might notice that some columns have large percentage (greater than 5%) of Null values. Drop all the rows which have Null values for such columns.

In [9]:
size=len(movies.index)
movies=movies[movies.isnull().sum(axis=1)<0.05*size]

-  ### Subtask 2.4: Drop unecessary rows

Some of the rows might have greater than five NaN values. Such rows aren't of much use for the analysis and hence, should be removed.

In [10]:
# Write your code for dropping the rows here
movies = movies[movies.isnull().sum(axis=1) <= 5]

-  ### Subtask 2.5: Fill NaN values

You might notice that the `language` column has some NaN values. Here, on inspection, you will see that it is safe to replace all the missing values with `'English'`.

In [11]:
# Write your code for filling the NaN values in the 'language' column here
movies['language']=movies['language'].fillna('English')
movies

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000
5,Andrew Stanton,462.0,73058679.0,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263700000.0,2012.0,6.6,24000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Scott Smith,1.0,NaN,Comedy|Drama,Eric Mabius,Signed Sealed Delivered,629,6.0,English,NaN,2013.0,7.7,84
5039,NaN,43.0,NaN,Crime|Drama|Mystery|Thriller,Natalie Zea,The Following,73839,359.0,English,NaN,NaN,7.5,32000
5040,Benjamin Roberds,13.0,NaN,Drama|Horror|Thriller,Eva Boehnke,A Plague So Pleasant,38,3.0,English,1400.0,2013.0,6.3,16
5041,Daniel Hsia,14.0,10443.0,Comedy|Drama|Romance,Alan Ruck,Shanghai Calling,1255,9.0,English,NaN,2012.0,6.3,660
5042,Jon Gunn,43.0,85222.0,Documentary,John August,My Date with Drew,4285,84.0,English,1100.0,2004.0,6.6,456

-  ### Subtask 2.6: Check the number of retained rows

You might notice that two of the columns viz. `num_critic_for_reviews` and `actor_1_name` have small percentages of NaN values left. You can let these columns as it is for now. Check the number and percentage of the rows retained after completing all the tasks above.

In [12]:
# Write your code for checking number of retained rows here
percent=len(movies.index)/5043*100
print(percent,'%')

99.9206821336506 %

**Checkpoint 1:** You might have noticed that we still have around `77%` of the rows!

## Task 3: Data Analysis

-  ### Subtask 3.1: Change the unit of columns

Convert the unit of the `budget` and `gross` columns from `$` to `million $`.

In [13]:
# Write your code for unit conversion here
def grossfun(x):
    return x/10000000
movies.gross=movies.gross.apply( grossfun)
movies.budget=movies.budget.apply(grossfun)
print(movies.gross)
print(movies.budget)

0       76.050585
1       30.940415
2       20.007417
3       44.813064
5        7.305868
          ...
5038          NaN
5039          NaN
5040          NaN
5041     0.001044
5042     0.008522
Name: gross, Length: 5039, dtype: float64
0       23.70000
1       30.00000
2       24.50000
3       25.00000
5       26.37000
          ...
5038         NaN
5039         NaN
5040     0.00014
5041         NaN
5042     0.00011
Name: budget, Length: 5039, dtype: float64

-  ### Subtask 3.2: Find the movies with highest profit

    1. Create a new column called `profit` which contains the difference of the two columns: `gross` and `budget`.
    2. Sort the dataframe using the `profit` column as reference.
    3. Extract the top ten profiting movies in descending order and store them in a new dataframe - `top10`

In [14]:
# Write your code for creating the profit column here
movies["profit"]=movies["gross"] - movies["budget"]
print(movies)

          director_name  num_critic_for_reviews      gross  \
0         James Cameron                   723.0  76.050585
1        Gore Verbinski                   302.0  30.940415
2            Sam Mendes                   602.0  20.007417
3     Christopher Nolan                   813.0  44.813064
5        Andrew Stanton                   462.0   7.305868
...                 ...                     ...        ...
5038        Scott Smith                     1.0        NaN
5039                NaN                    43.0        NaN
5040   Benjamin Roberds                    13.0        NaN
5041        Daniel Hsia                    14.0   0.001044
5042           Jon Gunn                    43.0   0.008522

                               genres     actor_1_name  \
0     Action|Adventure|Fantasy|Sci-Fi      CCH Pounder
1            Action|Adventure|Fantasy      Johnny Depp
2           Action|Adventure|Thriller  Christoph Waltz
3                     Action|Thriller        Tom Hardy
5             Action|Adventure|Sci-Fi     Daryl Sabara
...                               ...              ...
5038                     Comedy|Drama      Eric Mabius
5039     Crime|Drama|Mystery|Thriller      Natalie Zea
5040            Drama|Horror|Thriller      Eva Boehnke
5041             Comedy|Drama|Romance        Alan Ruck
5042                      Documentary      John August

                                    movie_title  num_voted_users  \
0                                       Avatar            886204
1     Pirates of the Caribbean: At World's End            471220
2                                      Spectre            275868
3                        The Dark Knight Rises           1144337
5                                  John Carter            212204
...                                         ...              ...
5038                   Signed Sealed Delivered               629
5039                 The Following                         73839
5040                      A Plague So Pleasant                38
5041                          Shanghai Calling              1255
5042                         My Date with Drew              4285

      num_user_for_reviews language    budget  title_year  imdb_score  \
0                   3054.0  English  23.70000      2009.0         7.9
1                   1238.0  English  30.00000      2007.0         7.1
2                    994.0  English  24.50000      2015.0         6.8
3                   2701.0  English  25.00000      2012.0         8.5
5                    738.0  English  26.37000      2012.0         6.6
...                    ...      ...       ...         ...         ...
5038                   6.0  English       NaN      2013.0         7.7
5039                 359.0  English       NaN         NaN         7.5
5040                   3.0  English   0.00014      2013.0         6.3
5041                   9.0  English       NaN      2012.0         6.3
5042                  84.0  English   0.00011      2004.0         6.6

      movie_facebook_likes     profit
0                    33000  52.350585
1                        0   0.940415
2                    85000  -4.492583
3                   164000  19.813064
5                    24000 -19.064132
...                    ...        ...
5038                    84        NaN
5039                 32000        NaN
5040                    16        NaN
5041                   660        NaN
5042                   456   0.008412

[5039 rows x 14 columns]

In [15]:
# Write your code for sorting the dataframe here
movies=movies.sort_values(by ="profit",ascending=False)

In [16]:
 # Write your code to get the top 10 profiting movies here
top10 =top10 =movies.head(10)
print(top10)

          director_name  num_critic_for_reviews      gross  \
0         James Cameron                   723.0  76.050585
29      Colin Trevorrow                   644.0  65.217727
26        James Cameron                   315.0  65.867230
3024       George Lucas                   282.0  46.093567
3080   Steven Spielberg                   215.0  43.494946
794         Joss Whedon                   703.0  62.327955
17          Joss Whedon                   703.0  62.327955
509        Roger Allers                   186.0  42.278378
240        George Lucas                   320.0  47.454468
66    Christopher Nolan                   645.0  53.331606

                                        genres         actor_1_name  \
0              Action|Adventure|Fantasy|Sci-Fi          CCH Pounder
29            Action|Adventure|Sci-Fi|Thriller  Bryce Dallas Howard
26                               Drama|Romance    Leonardo DiCaprio
3024           Action|Adventure|Fantasy|Sci-Fi        Harrison Ford
3080                             Family|Sci-Fi         Henry Thomas
794                    Action|Adventure|Sci-Fi      Chris Hemsworth
17                     Action|Adventure|Sci-Fi      Chris Hemsworth
509   Adventure|Animation|Drama|Family|Musical    Matthew Broderick
240            Action|Adventure|Fantasy|Sci-Fi      Natalie Portman
66                 Action|Crime|Drama|Thriller       Christian Bale

                                     movie_title  num_voted_users  \
0                                        Avatar            886204
29                               Jurassic World            418214
26                                      Titanic            793059
3024         Star Wars: Episode IV - A New Hope            911097
3080                 E.T. the Extra-Terrestrial            281842
794                                The Avengers            995415
17                                 The Avengers            995415
509                               The Lion King            644348
240   Star Wars: Episode I - The Phantom Menace            534658
66                              The Dark Knight           1676169

      num_user_for_reviews language  budget  title_year  imdb_score  \
0                   3054.0  English   23.70      2009.0         7.9
29                  1290.0  English   15.00      2015.0         7.0
26                  2528.0  English   20.00      1997.0         7.7
3024                1470.0  English    1.10      1977.0         8.7
3080                 515.0  English    1.05      1982.0         7.9
794                 1722.0  English   22.00      2012.0         8.1
17                  1722.0  English   22.00      2012.0         8.1
509                  656.0  English    4.50      1994.0         8.5
240                 3597.0  English   11.50      1999.0         6.5
66                  4667.0  English   18.50      2008.0         9.0

      movie_facebook_likes     profit
0                    33000  52.350585
29                  150000  50.217727
26                   26000  45.867230
3024                 33000  44.993567
3080                 34000  42.444946
794                 123000  40.327955
17                  123000  40.327955
509                  17000  37.778378
240                  13000  35.954468
66                   37000  34.831606

-  ### Subtask 3.3: Drop duplicate values

After you found out the top 10 profiting movies, you might have notice a duplicate value. So, it seems like the dataframe has duplicate values as well. Drop the duplicate values from the dataframe and repeat `Subtask 3.2`.

In [17]:
# Write your code for dropping duplicate values here
movies.drop_duplicates()

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,76.050585,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,23.700000,2009.0,7.9,33000,52.350585
29,Colin Trevorrow,644.0,65.217727,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,15.000000,2015.0,7.0,150000,50.217727
26,James Cameron,315.0,65.867230,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,20.000000,1997.0,7.7,26000,45.867230
3024,George Lucas,282.0,46.093567,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,1.100000,1977.0,8.7,33000,44.993567
3080,Steven Spielberg,215.0,43.494946,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,1.050000,1982.0,7.9,34000,42.444946
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5036,Anthony Vallone,NaN,NaN,Crime|Drama,Richard Jewell,The Mongol King,36,1.0,English,0.000325,2005.0,7.8,4,NaN
5038,Scott Smith,1.0,NaN,Comedy|Drama,Eric Mabius,Signed Sealed Delivered,629,6.0,English,NaN,2013.0,7.7,84,NaN
5039,NaN,43.0,NaN,Crime|Drama|Mystery|Thriller,Natalie Zea,The Following,73839,359.0,English,NaN,NaN,7.5,32000,NaN
5040,Benjamin Roberds,13.0,NaN,Drama|Horror|Thriller,Eva Boehnke,A Plague So Pleasant,38,3.0,English,0.000140,2013.0,6.3,16,NaN
5041,Daniel Hsia,14.0,0.001044,Comedy|Drama|Romance,Alan Ruck,Shanghai Calling,1255,9.0,English,NaN,2012.0,6.3,660,NaN

In [18]:
# Write code for repeating subtask 2 here
movies["profit"]=movies["gross"] - movies["budget"]
movies=movies.sort_values(by ="profit",ascending=False) 
top10 =movies.head(10)
print(top10)

          director_name  num_critic_for_reviews      gross  \
0         James Cameron                   723.0  76.050585
29      Colin Trevorrow                   644.0  65.217727
26        James Cameron                   315.0  65.867230
3024       George Lucas                   282.0  46.093567
3080   Steven Spielberg                   215.0  43.494946
794         Joss Whedon                   703.0  62.327955
17          Joss Whedon                   703.0  62.327955
509        Roger Allers                   186.0  42.278378
240        George Lucas                   320.0  47.454468
66    Christopher Nolan                   645.0  53.331606

                                        genres         actor_1_name  \
0              Action|Adventure|Fantasy|Sci-Fi          CCH Pounder
29            Action|Adventure|Sci-Fi|Thriller  Bryce Dallas Howard
26                               Drama|Romance    Leonardo DiCaprio
3024           Action|Adventure|Fantasy|Sci-Fi        Harrison Ford
3080                             Family|Sci-Fi         Henry Thomas
794                    Action|Adventure|Sci-Fi      Chris Hemsworth
17                     Action|Adventure|Sci-Fi      Chris Hemsworth
509   Adventure|Animation|Drama|Family|Musical    Matthew Broderick
240            Action|Adventure|Fantasy|Sci-Fi      Natalie Portman
66                 Action|Crime|Drama|Thriller       Christian Bale

                                     movie_title  num_voted_users  \
0                                        Avatar            886204
29                               Jurassic World            418214
26                                      Titanic            793059
3024         Star Wars: Episode IV - A New Hope            911097
3080                 E.T. the Extra-Terrestrial            281842
794                                The Avengers            995415
17                                 The Avengers            995415
509                               The Lion King            644348
240   Star Wars: Episode I - The Phantom Menace            534658
66                              The Dark Knight           1676169

      num_user_for_reviews language  budget  title_year  imdb_score  \
0                   3054.0  English   23.70      2009.0         7.9
29                  1290.0  English   15.00      2015.0         7.0
26                  2528.0  English   20.00      1997.0         7.7
3024                1470.0  English    1.10      1977.0         8.7
3080                 515.0  English    1.05      1982.0         7.9
794                 1722.0  English   22.00      2012.0         8.1
17                  1722.0  English   22.00      2012.0         8.1
509                  656.0  English    4.50      1994.0         8.5
240                 3597.0  English   11.50      1999.0         6.5
66                  4667.0  English   18.50      2008.0         9.0

      movie_facebook_likes     profit
0                    33000  52.350585
29                  150000  50.217727
26                   26000  45.867230
3024                 33000  44.993567
3080                 34000  42.444946
794                 123000  40.327955
17                  123000  40.327955
509                  17000  37.778378
240                  13000  35.954468
66                   37000  34.831606

**Checkpoint 2:** You might spot two movies directed by `James Cameron` in the list.

-  ### Subtask 3.4: Find IMDb Top 250

    1. Create a new dataframe `IMDb_Top_250` and store the top 250 movies with the highest IMDb Rating (corresponding to the column: `imdb_score`). Also make sure that for all of these movies, the `num_voted_users` is greater than 25,000.
Also add a `Rank` column containing the values 1 to 250 indicating the ranks of the corresponding films.
    2. Extract all the movies in the `IMDb_Top_250` dataframe which are not in the English language and store them in a new dataframe named `Top_Foreign_Lang_Film`.

In [19]:
# Write your code for extracting the top 250 movies as per the IMDb score here. Make sure that you store it in a new dataframe 
# and name that dataframe as 'IMDb_Top_250'
movies=movies.sort_values(by ="imdb_score",ascending=False)
IMDb_Top_250=movies.head(250)
IMDb_Top_250

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
2765,John Blanchard,NaN,NaN,Comedy,Martin Short,Towering Inferno,10,NaN,English,NaN,NaN,9.5,0,NaN
1937,Frank Darabont,199.0,2.834147,Crime|Drama,Morgan Freeman,The Shawshank Redemption,1689764,4144.0,English,2.50,1994.0,9.3,108000,0.334147
3466,Francis Ford Coppola,208.0,13.482195,Crime|Drama,Al Pacino,The Godfather,1155770,2238.0,English,0.60,1972.0,9.2,43000,12.882195
4409,John Stockwell,2.0,NaN,Action,Matthew Ziff,Kickboxer: Vengeance,246,1.0,English,1.70,2016.0,9.1,0,NaN
3207,NaN,53.0,0.044709,Drama,Krystyna Janda,Dekalog,12591,37.0,Polish,NaN,NaN,9.1,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4461,Thomas Vinterberg,98.0,0.164778,Drama,Ulrich Thomsen,The Celebration,65951,258.0,Danish,0.13,1998.0,8.1,5000,0.034778
4157,Victor Fleming,213.0,2.220261,Adventure|Family|Fantasy|Musical,Margaret Hamilton,The Wizard of Oz,291875,533.0,English,0.28,1939.0,8.1,14000,1.940261
2914,Je-kyu Kang,86.0,0.111019,Action|Drama|War,Min-sik Choi,Tae Guk Gi: The Brotherhood of War,31943,224.0,Korean,1.28,2004.0,8.1,0,-1.168981
3575,James Cameron,204.0,3.840000,Action|Sci-Fi,Michael Biehn,The Terminator,600266,692.0,English,0.65,1984.0,8.1,13000,3.190000
179,Alejandro G. Iñárritu,556.0,18.363592,Adventure|Drama|Thriller|Western,Leonardo DiCaprio,The Revenant,406020,1188.0,English,13.50,2015.0,8.1,190000,4.863592

In [20]:
Top_Foreign_Lang_Film=IMDb_Top_250[IMDb_Top_250["language"] != "English"]
Top_Foreign_Lang_Film
# Write your code to extract top foreign language films from 'IMDb_Top_250' here

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
3207,NaN,53.0,0.044709,Drama,Krystyna Janda,Dekalog,12591,37.0,Polish,NaN,NaN,9.1,0,NaN
2824,NaN,53.0,0.044709,Drama,Krystyna Janda,Dekalog,12590,37.0,Polish,NaN,NaN,9.1,0,NaN
4498,Sergio Leone,181.0,0.610000,Western,Clint Eastwood,"The Good, the Bad and the Ugly",503509,780.0,Italian,0.120000,1966.0,8.9,20000,0.490000
4747,Akira Kurosawa,153.0,0.026906,Action|Adventure|Drama,Takashi Shimura,Seven Samurai,229012,596.0,Japanese,0.200000,1954.0,8.7,11000,-0.173094
3579,NaN,10.0,NaN,Crime|Drama|Thriller,Maria Pia Calzone,Gomorrah,9638,25.0,Italian,NaN,NaN,8.7,0,NaN
4029,Fernando Meirelles,214.0,0.756340,Crime|Drama,Alice Braga,City of God,533200,749.0,Portuguese,0.330000,2002.0,8.7,28000,0.426340
2373,Hayao Miyazaki,246.0,1.004989,Adventure|Animation|Family|Fantasy,Bunta Sugawara,Spirited Away,417971,902.0,Japanese,1.900000,2001.0,8.6,28000,-0.895011
4921,Majid Majidi,46.0,0.092540,Drama|Family,Bahare Seddiqi,Children of Heaven,27882,130.0,Persian,0.018000,1997.0,8.5,0,0.074540
3870,Raja Menon,39.0,NaN,Action|Drama|History|Thriller|War,Nimrat Kaur,Airlift,30977,178.0,Hindi,0.440000,2016.0,8.5,10000,NaN
3931,Ron Fricke,115.0,0.260185,Documentary|Music,Collin Alfredo St. Dic,Samsara,22457,69.0,None,0.400000,2011.0,8.5,26000,-0.139815
4259,Florian Henckel von Donnersmarck,215.0,1.128466,Drama|Thriller,Sebastian Koch,The Lives of Others,259379,407.0,German,0.200000,2006.0,8.5,39000,0.928466
1329,S.S. Rajamouli,44.0,0.649800,Action|Adventure|Drama|Fantasy|War,Tamannaah Bhatia,Baahubali: The Beginning,62756,410.0,Telugu,1.802615,2015.0,8.4,21000,-1.152815
2970,Wolfgang Petersen,96.0,1.143313,Adventure|Drama|Thriller|War,Jürgen Prochnow,Das Boot,168203,426.0,German,1.400000,1981.0,8.4,11000,-0.256687
4105,Chan-wook Park,305.0,0.218129,Drama|Mystery|Thriller,Min-sik Choi,Oldboy,356181,809.0,Korean,0.300000,2003.0,8.4,43000,-0.081871
4659,Asghar Farhadi,354.0,0.709849,Drama|Mystery,Shahab Hosseini,A Separation,151812,264.0,Persian,0.050000,2011.0,8.4,48000,0.659849
3685,Rakeysh Omprakash Mehra,33.0,0.219733,Comedy|Drama|History|Romance,Anupam Kher,Rang De Basanti,70233,321.0,Hindi,NaN,2006.0,8.4,0,NaN
1298,Jean-Pierre Jeunet,242.0,3.320166,Comedy|Romance,Mathieu Kassovitz,Amélie,534262,1314.0,French,7.700000,2001.0,8.4,39000,-4.379834
2323,Hayao Miyazaki,174.0,0.229819,Adventure|Animation|Fantasy,Minnie Driver,Princess Mononoke,221552,570.0,Japanese,240.000000,1997.0,8.4,11000,-239.770181
2734,Fritz Lang,260.0,0.002644,Drama|Sci-Fi,Brigitte Helm,Metropolis,111841,413.0,German,0.600000,1927.0,8.3,12000,-0.597356
4033,Thomas Vinterberg,349.0,0.061097,Drama,Thomas Bo Larsen,The Hunt,170155,249.0,Danish,0.380000,2012.0,8.3,60000,-0.318903
2829,Oliver Hirschbiegel,192.0,0.550194,Biography|Drama|History|War,Thomas Kretschmann,Downfall,248354,564.0,German,1.350000,2004.0,8.3,14000,-0.799806
1133,NaN,23.0,NaN,Drama|Fantasy|Horror|Mystery,Pierre Perrier,The Returned,15762,47.0,French,NaN,NaN,8.3,17000,NaN
1710,NaN,16.0,NaN,Crime|Drama|Thriller,Ólafur Darri Ólafsson,Trapped,2308,19.0,Icelandic,NaN,NaN,8.2,0,NaN
204,Hideaki Anno,1.0,NaN,Action|Adventure|Drama|Horror|Sci-Fi,Mark Chinnery,Godzilla Resurgence,374,13.0,Japanese,NaN,2016.0,8.2,0,NaN
2047,Hayao Miyazaki,212.0,0.471046,Adventure|Animation|Family|Fantasy,Christian Bale,Howl's Moving Castle,214091,330.0,Japanese,2.400000,2004.0,8.2,13000,-1.928954
4160,Rajkumar Hirani,15.0,NaN,Comedy|Drama|Romance,Vidya Balan,Lage Raho Munna Bhai,27569,106.0,Hindi,12.000000,2006.0,8.2,349,NaN
98,Hideaki Anno,1.0,NaN,Action|Adventure|Drama|Horror|Sci-Fi,Mark Chinnery,Godzilla Resurgence,374,13.0,Japanese,NaN,2016.0,8.2,0,NaN
4809,Ingmar Bergman,76.0,NaN,Drama,Liv Ullmann,Cries & Whispers,19964,197.0,Swedish,0.040000,1972.0,8.2,0,NaN
3550,Denis Villeneuve,226.0,0.685710,Drama|Mystery|War,Lubna Azabal,Incendies,80429,156.0,French,0.680000,2010.0,8.2,37000,0.005710
4945,Amal Al-Agroobi,NaN,NaN,Documentary|Family,NaN,The Brain That Sings,18,NaN,Arabic,0.012500,2013.0,8.2,54,NaN
4000,Juan José Campanella,262.0,2.016742,Drama|Mystery|Thriller,Ricardo Darín,The Secret in Their Eyes,131831,231.0,Spanish,0.200000,2009.0,8.2,33000,1.816742
2551,Guillermo del Toro,406.0,3.762314,Drama|Fantasy|War,Ivana Baquero,Pan's Labyrinth,467234,1083.0,Spanish,1.350000,2006.0,8.2,27000,2.412314
4585,Joshua Oppenheimer,248.0,0.048422,Biography|Crime|Documentary|History,Anwar Congo,The Act of Killing,23836,107.0,Indonesian,0.100000,2012.0,8.2,20000,-0.051578
4348,Jehane Noujaim,68.0,NaN,Documentary|Drama|History|News,Khalid Abdalla,The Square,6678,42.0,Arabic,0.150000,2013.0,8.1,0,NaN
3423,Katsuhiro Ôtomo,150.0,0.043916,Action|Animation|Sci-Fi,Mitsuo Iwata,Akira,106160,430.0,Japanese,110.000000,1988.0,8.1,0,-109.956084
4267,Alejandro G. Iñárritu,157.0,0.538383,Drama|Thriller,Adriana Barraza,Amores Perros,173551,361.0,Spanish,0.200000,2000.0,8.1,11000,0.338383
1061,Andrei Tarkovsky,144.0,NaN,Drama|Mystery|Sci-Fi,Donatas Banionis,Solaris,54057,236.0,Russian,0.100000,1972.0,8.1,0,NaN
4912,Carl Theodor Dreyer,54.0,NaN,Drama|Fantasy,Hanne Aagesen,Ordet,9903,49.0,Danish,NaN,1955.0,8.1,863,NaN
2870,Niels Arden Oplev,NaN,NaN,Action|Crime|Mystery|Thriller,Michael Nyqvist,Del 1 - Män som hatar kvinnor,335,NaN,Swedish,NaN,NaN,8.1,22,NaN
3553,José Padilha,142.0,0.000806,Action|Crime|Drama|Thriller,Wagner Moura,Elite Squad,81644,107.0,Portuguese,0.400000,2007.0,8.1,11000,-0.399194
4682,Bernardo Bertolucci,120.0,NaN,Drama,Jean-Louis Trintignant,The Conformist,17813,101.0,Italian,0.075000,1970.0,8.1,0,NaN
2830,Alejandro Amenábar,157.0,0.208635,Biography|Drama|Romance,Belén Rueda,The Sea Inside,64556,140.0,Spanish,1.000000,2004.0,8.1,0,-0.791365
4461,Thomas Vinterberg,98.0,0.164778,Drama,Ulrich Thomsen,The Celebration,65951,258.0,Danish,0.130000,1998.0,8.1,5000,0.034778
2914,Je-kyu Kang,86.0,0.111019,Action|Drama|War,Min-sik Choi,Tae Guk Gi: The Brotherhood of War,31943,224.0,Korean,1.280000,2004.0,8.1,0,-1.168981

**Checkpoint 3:** Can you spot `Veer-Zaara` in the dataframe?

- ### Subtask 3.5: Find the best directors

    1. Group the dataframe using the `director_name` column.
    2. Find out the top 10 directors for whom the mean of `imdb_score` is the highest and store them in a new dataframe `top10director`.

In [21]:
# Write your code for extracting the top 10 directors here
director = movies.pivot_table(values = 'imdb_score', index = 'director_name', aggfunc = 'mean')
director = director.sort_values(by = 'imdb_score', ascending = False)
director = director.head(10)
director

                  imdb_score
director_name
John Blanchard           9.5
Cary Bell                8.7
Mitchell Altieri         8.7
Sadyk Sher-Niyaz         8.7
Charles Chaplin          8.6
Mike Mayhall             8.6
Ron Fricke               8.5
Majid Majidi             8.5
Damien Chazelle          8.5
Raja Menon               8.5

**Checkpoint 4:** No surprises that `Damien Chazelle` (director of Whiplash and La La Land) is in this list.

-  ### Subtask 3.6: Find popular genres

You might have noticed the `genres` column in the dataframe with all the genres of the movies seperated by a pipe (`|`). Out of all the movie genres, the first two are most significant for any film.

1. Extract the first two genres from the `genres` column and store them in two new columns: `genre_1` and `genre_2`. Some of the movies might have only one genre. In such cases, extract the single genre into both the columns, i.e. for such movies the `genre_2` will be the same as `genre_1`.
2. Group the dataframe using `genre_1` as the primary column and `genre_2` as the secondary column.
3. Find out the 5 most popular combo of genres by finding the mean of the gross values using the `gross` column and store them in a new dataframe named `PopGenre`.

In [22]:
# Write your code for extracting the first two genres of each movie here
movies["genre_1"] = movies["genres"].str.split("|").str.get(0)
movies["genre_2"] = movies["genres"].str.split("|").str.get(1)
movies["genre_2"] = movies["genre_2"].fillna(movies["genre_1"])
movies.head()

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
2765,John Blanchard,NaN,NaN,Comedy,Martin Short,Towering Inferno,10,NaN,English,NaN,NaN,9.5,0,NaN,Comedy,Comedy
1937,Frank Darabont,199.0,2.834147,Crime|Drama,Morgan Freeman,The Shawshank Redemption,1689764,4144.0,English,2.5,1994.0,9.3,108000,0.334147,Crime,Drama
3466,Francis Ford Coppola,208.0,13.482195,Crime|Drama,Al Pacino,The Godfather,1155770,2238.0,English,0.6,1972.0,9.2,43000,12.882195,Crime,Drama
4409,John Stockwell,2.0,NaN,Action,Matthew Ziff,Kickboxer: Vengeance,246,1.0,English,1.7,2016.0,9.1,0,NaN,Action,Action
3207,NaN,53.0,0.044709,Drama,Krystyna Janda,Dekalog,12591,37.0,Polish,NaN,NaN,9.1,0,NaN,Drama,Drama

In [23]:
movies_by_segment =movies.groupby(['genre_1','genre_2'])
# Write your code for grouping the dataframe here

In [24]:
PopGenre = pd.DataFrame(movies_by_segment.gross.mean()).sort_values("gross", ascending = False).head()
PopGenre
# Write your code for getting the 5 most popular combo of genres here

                         gross
genre_1   genre_2
Family    Sci-Fi     43.494946
Adventure Sci-Fi     22.862776
          Animation  11.705001
          Family     11.329941
Action    Adventure  10.954002

**Checkpoint 5:** Well, as it turns out. `Family + Sci-Fi` is the most popular combo of genres out there!

-  ### Subtask 3.7: Find the critic-favorite and audience-favorite actors

    1. Create three new dataframes namely, `Meryl_Streep`, `Leo_Caprio`, and `Brad_Pitt` which contain the movies in which the actors: 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' are the lead actors. Use only the `actor_1_name` column for extraction. Also, make sure that you use the names 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' for the said extraction.
    2. Append the rows of all these dataframes and store them in a new dataframe named `Combined`.
    3. Group the combined dataframe using the `actor_1_name` column.
    4. Find the mean of the `num_critic_for_reviews` and `num_user_for_review` and identify the actors which have the highest mean.

In [25]:
# Write your code for creating three new dataframes here

Meryl_Streep = pd.DataFrame(movies_by_segment.gross.mean()).sort_values("gross", ascending = False).head()
PopGenre
# Include all movies in which Meryl_Streep is the lead

                         gross
genre_1   genre_2
Family    Sci-Fi     43.494946
Adventure Sci-Fi     22.862776
          Animation  11.705001
          Family     11.329941
Action    Adventure  10.954002

In [26]:
Leo_Caprio = Leo_Caprio = movies[movies["actor_1_name"] == "Leonardo DiCaprio"]
Leo_Caprio 
# Include all movies in which Leo_Caprio is the lead

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
97,Christopher Nolan,642.0,29.256885,Action|Adventure|Sci-Fi|Thriller,Leonardo DiCaprio,Inception,1468200,2803.0,English,16.00,2010.0,8.8,175000,13.256885,Action,Adventure
296,Quentin Tarantino,765.0,16.280465,Drama|Western,Leonardo DiCaprio,Django Unchained,955174,1193.0,English,10.00,2012.0,8.5,199000,6.280465,Drama,Western
361,Martin Scorsese,352.0,13.237344,Crime|Drama|Thriller,Leonardo DiCaprio,The Departed,873649,2054.0,English,9.00,2006.0,8.5,29000,4.237344,Crime,Drama
308,Martin Scorsese,606.0,11.686673,Biography|Comedy|Crime|Drama,Leonardo DiCaprio,The Wolf of Wall Street,780588,1138.0,English,10.00,2013.0,8.2,138000,1.686673,Biography,Comedy
452,Martin Scorsese,490.0,12.796841,Mystery|Thriller,Leonardo DiCaprio,Shutter Island,786092,964.0,English,8.00,2010.0,8.1,53000,4.796841,Mystery,Thriller
179,Alejandro G. Iñárritu,556.0,18.363592,Adventure|Drama|Thriller|Western,Leonardo DiCaprio,The Revenant,406020,1188.0,English,13.50,2015.0,8.1,190000,4.863592,Adventure,Drama
911,Steven Spielberg,194.0,16.443522,Biography|Crime|Drama,Leonardo DiCaprio,Catch Me If You Can,525801,667.0,English,5.20,2002.0,8.0,15000,11.243522,Biography,Crime
307,Edward Zwick,166.0,5.736626,Adventure|Drama|Thriller,Leonardo DiCaprio,Blood Diamond,400292,657.0,English,10.00,2006.0,8.0,14000,-4.263374,Adventure,Drama
26,James Cameron,315.0,65.867230,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,20.00,1997.0,7.7,26000,45.867230,Drama,Romance
257,Martin Scorsese,267.0,10.260883,Biography|Drama,Leonardo DiCaprio,The Aviator,264318,799.0,English,11.00,2004.0,7.5,0,-0.739117,Biography,Drama
326,Martin Scorsese,233.0,7.767964,Crime|Drama,Leonardo DiCaprio,Gangs of New York,314033,1166.0,English,10.00,2002.0,7.5,0,-2.232036,Crime,Drama
1114,Sam Mendes,323.0,2.287781,Drama|Romance,Leonardo DiCaprio,Revolutionary Road,152591,414.0,English,3.50,2008.0,7.3,0,-1.212219,Drama,Romance
3476,Baz Luhrmann,490.0,14.481280,Drama|Romance,Leonardo DiCaprio,The Great Gatsby,362933,753.0,English,10.50,2013.0,7.3,115000,3.981280,Drama,Romance
50,Baz Luhrmann,490.0,14.481280,Drama|Romance,Leonardo DiCaprio,The Great Gatsby,362912,753.0,English,10.50,2013.0,7.3,115000,3.981280,Drama,Romance
641,Ridley Scott,238.0,3.938044,Action|Drama|Thriller,Leonardo DiCaprio,Body of Lies,174248,263.0,English,7.00,2008.0,7.1,0,-3.061956,Action,Drama
2757,Baz Luhrmann,106.0,4.633873,Drama|Romance,Leonardo DiCaprio,Romeo + Juliet,167750,506.0,English,1.45,1996.0,6.8,10000,3.183873,Drama,Romance
2067,Jerry Zaks,45.0,1.278251,Drama,Leonardo DiCaprio,Marvin's Room,20163,71.0,English,2.30,1996.0,6.7,1000,-1.021749,Drama,Drama
1453,Clint Eastwood,392.0,3.730495,Biography|Crime|Drama,Leonardo DiCaprio,J. Edgar,102728,279.0,English,3.50,2011.0,6.6,16000,0.230495,Biography,Crime
990,Danny Boyle,118.0,3.977860,Adventure|Drama|Thriller,Leonardo DiCaprio,The Beach,176169,548.0,English,5.00,2000.0,6.6,0,-1.022140,Adventure,Drama
1422,Randall Wallace,83.0,5.687636,Action|Adventure,Leonardo DiCaprio,The Man in the Iron Mask,125219,244.0,English,3.50,1998.0,6.4,0,2.187636,Action,Adventure
1560,Sam Raimi,63.0,1.863654,Action|Thriller|Western,Leonardo DiCaprio,The Quick and the Dead,69197,216.0,English,3.20,1995.0,6.4,0,-1.336346,Action,Thriller

In [27]:
Brad_Pitt = Brad_Pitt = movies[movies["actor_1_name"] == "Brad Pitt"]
Brad_Pitt.head()
# Include all movies in which Brad_Pitt is the lead

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
683,David Fincher,315.0,3.702339,Drama,Brad Pitt,Fight Club,1347461,2968.0,English,6.3,1999.0,8.8,48000,-2.597660,Drama,Drama
2898,Tony Scott,122.0,1.228150,Action|Crime|Drama|Romance|Thriller,Brad Pitt,True Romance,163492,460.0,English,1.3,1993.0,8.0,15000,-0.071850,Action,Crime
101,David Fincher,362.0,12.749080,Drama|Fantasy|Romance,Brad Pitt,The Curious Case of Benjamin Button,459346,822.0,English,15.0,2008.0,7.8,23000,-2.250920,Drama,Fantasy
400,Steven Soderbergh,186.0,18.340577,Crime|Thriller,Brad Pitt,Ocean's Eleven,402645,845.0,English,8.5,2001.0,7.8,0,9.840577,Crime,Thriller
470,David Ayer,406.0,8.570712,Action|Drama|War,Brad Pitt,Fury,303185,701.0,English,6.8,2014.0,7.6,82000,1.770712,Action,Drama

In [28]:
# Write your code for combining the three dataframes here
combined = pd.concat([Meryl_Streep,Leo_Caprio,Brad_Pitt ], axis = 0)
combined

,gross,director_name,num_critic_for_reviews,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
"(Family, Sci-Fi)",43.494946,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(Adventure, Sci-Fi)",22.862776,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(Adventure, Animation)",11.705001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(Adventure, Family)",11.329941,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(Action, Adventure)",10.954002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,29.256885,Christopher Nolan,642.0,Action|Adventure|Sci-Fi|Thriller,Leonardo DiCaprio,Inception,1468200.0,2803.0,English,16.00,2010.0,8.8,175000.0,13.256885,Action,Adventure
296,16.280465,Quentin Tarantino,765.0,Drama|Western,Leonardo DiCaprio,Django Unchained,955174.0,1193.0,English,10.00,2012.0,8.5,199000.0,6.280465,Drama,Western
361,13.237344,Martin Scorsese,352.0,Crime|Drama|Thriller,Leonardo DiCaprio,The Departed,873649.0,2054.0,English,9.00,2006.0,8.5,29000.0,4.237344,Crime,Drama
308,11.686673,Martin Scorsese,606.0,Biography|Comedy|Crime|Drama,Leonardo DiCaprio,The Wolf of Wall Street,780588.0,1138.0,English,10.00,2013.0,8.2,138000.0,1.686673,Biography,Comedy
452,12.796841,Martin Scorsese,490.0,Mystery|Thriller,Leonardo DiCaprio,Shutter Island,786092.0,964.0,English,8.00,2010.0,8.1,53000.0,4.796841,Mystery,Thriller
179,18.363592,Alejandro G. Iñárritu,556.0,Adventure|Drama|Thriller|Western,Leonardo DiCaprio,The Revenant,406020.0,1188.0,English,13.50,2015.0,8.1,190000.0,4.863592,Adventure,Drama
911,16.443522,Steven Spielberg,194.0,Biography|Crime|Drama,Leonardo DiCaprio,Catch Me If You Can,525801.0,667.0,English,5.20,2002.0,8.0,15000.0,11.243522,Biography,Crime
307,5.736626,Edward Zwick,166.0,Adventure|Drama|Thriller,Leonardo DiCaprio,Blood Diamond,400292.0,657.0,English,10.00,2006.0,8.0,14000.0,-4.263374,Adventure,Drama
26,65.867230,James Cameron,315.0,Drama|Romance,Leonardo DiCaprio,Titanic,793059.0,2528.0,English,20.00,1997.0,7.7,26000.0,45.867230,Drama,Romance
257,10.260883,Martin Scorsese,267.0,Biography|Drama,Leonardo DiCaprio,The Aviator,264318.0,799.0,English,11.00,2004.0,7.5,0.0,-0.739117,Biography,Drama
326,7.767964,Martin Scorsese,233.0,Crime|Drama,Leonardo DiCaprio,Gangs of New York,314033.0,1166.0,English,10.00,2002.0,7.5,0.0,-2.232036,Crime,Drama
1114,2.287781,Sam Mendes,323.0,Drama|Romance,Leonardo DiCaprio,Revolutionary Road,152591.0,414.0,English,3.50,2008.0,7.3,0.0,-1.212219,Drama,Romance
3476,14.481280,Baz Luhrmann,490.0,Drama|Romance,Leonardo DiCaprio,The Great Gatsby,362933.0,753.0,English,10.50,2013.0,7.3,115000.0,3.981280,Drama,Romance
50,14.481280,Baz Luhrmann,490.0,Drama|Romance,Leonardo DiCaprio,The Great Gatsby,362912.0,753.0,English,10.50,2013.0,7.3,115000.0,3.981280,Drama,Romance
641,3.938044,Ridley Scott,238.0,Action|Drama|Thriller,Leonardo DiCaprio,Body of Lies,174248.0,263.0,English,7.00,2008.0,7.1,0.0,-3.061956,Action,Drama
2757,4.633873,Baz Luhrmann,106.0,Drama|Romance,Leonardo DiCaprio,Romeo + Juliet,167750.0,506.0,English,1.45,1996.0,6.8,10000.0,3.183873,Drama,Romance
2067,1.278251,Jerry Zaks,45.0,Drama,Leonardo DiCaprio,Marvin's Room,20163.0,71.0,English,2.30,1996.0,6.7,1000.0,-1.021749,Drama,Drama
1453,3.730495,Clint Eastwood,392.0,Biography|Crime|Drama,Leonardo DiCaprio,J. Edgar,102728.0,279.0,English,3.50,2011.0,6.6,16000.0,0.230495,Biography,Crime
990,3.977860,Danny Boyle,118.0,Adventure|Drama|Thriller,Leonardo DiCaprio,The Beach,176169.0,548.0,English,5.00,2000.0,6.6,0.0,-1.022140,Adventure,Drama
1422,5.687636,Randall Wallace,83.0,Action|Adventure,Leonardo DiCaprio,The Man in the Iron Mask,125219.0,244.0,English,3.50,1998.0,6.4,0.0,2.187636,Action,Adventure
1560,1.863654,Sam Raimi,63.0,Action|Thriller|Western,Leonardo DiCaprio,The Quick and the Dead,69197.0,216.0,English,3.20,1995.0,6.4,0.0,-1.336346,Action,Thriller
683,3.702339,David Fincher,315.0,Drama,Brad Pitt,Fight Club,1347461.0,2968.0,English,6.30,1999.0,8.8,48000.0,-2.597660,Drama,Drama
2898,1.228150,Tony Scott,122.0,Action|Crime|Drama|Romance|Thriller,Brad Pitt,True Romance,163492.0,460.0,English,1.30,1993.0,8.0,15000.0,-0.071850,Action,Crime
101,12.749080,David Fincher,362.0,Drama|Fantasy|Romance,Brad Pitt,The Curious Case of Benjamin Button,459346.0,822.0,English,15.00,2008.0,7.8,23000.0,-2.250920,Drama,Fantasy
400,18.340577,Steven Soderbergh,186.0,Crime|Thriller,Brad Pitt,Ocean's Eleven,402645.0,845.0,English,8.50,2001.0,7.8,0.0,9.840577,Crime,Thriller
470,8.570712,David Ayer,406.0,Action|Drama|War,Brad Pitt,Fury,303185.0,701.0,English,6.80,2014.0,7.6,82000.0,1.770712,Action,Drama
940,10.526461,Neil Jordan,120.0,Drama|Fantasy|Horror,Brad Pitt,Interview with the Vampire: The Vampire Chroni...,239752.0,406.0,English,6.00,1994.0,7.6,11000.0,4.526461,Drama,Fantasy
1722,0.390498,Andrew Dominik,273.0,Biography|Crime|Drama|History|Western,Brad Pitt,The Assassination of Jesse James by the Coward...,136104.0,415.0,English,3.00,2007.0,7.5,0.0,-2.609502,Biography,Crime
2204,3.430077,Alejandro G. Iñárritu,285.0,Drama,Brad Pitt,Babel,243799.0,908.0,English,2.50,2006.0,7.5,0.0,0.930077,Drama,Drama
147,13.322835,Wolfgang Petersen,220.0,Adventure,Brad Pitt,Troy,381672.0,1694.0,English,17.50,2004.0,7.2,0.0,-4.177165,Adventure,Adventure
611,3.790151,Jean-Jacques Annaud,76.0,Adventure|Biography|Drama|History|War,Brad Pitt,Seven Years in Tibet,96385.0,119.0,English,7.00,1997.0,7.0,0.0,-3.209849,Adventure,Biography
382,0.002687,Tony Scott,142.0,Action|Crime|Thriller,Brad Pitt,Spy Game,121259.0,361.0,English,9.20,2001.0,7.0,0.0,-9.197313,Action,Crime
792,2.628832,Patrick Gilmore,98.0,Adventure|Animation|Comedy|Drama|Family|Fantas...,Brad Pitt,Sinbad: Legend of the Seven Seas,36144.0,91.0,English,6.00,2003.0,6.7,880.0,-3.371168,Adventure,Animation
1490,1.330332,Terrence Malick,584.0,Drama|Fantasy,Brad Pitt,The Tree of Life,136367.0,975.0,English,3.20,2011.0,6.7,39000.0,-1.869668,Drama,Fantasy
255,18.633610,Doug Liman,233.0,Action|Comedy|Crime|Romance|Thriller,Brad Pitt,Mr. & Mrs. Smith,348861.0,798.0,English,12.00,2005.0,6.5,0.0,6.633610,Action,Comedy
254,12.553163,Steven Soderbergh,198.0,Crime|Thriller,Brad Pitt,Ocean's Twelve,284852.0,627.0,English,11.00,2004.0,6.4,0.0,1.553163,Crime,Thriller
2682,1.493857,Andrew Dominik,414.0,Crime|Thriller,Brad Pitt,Killing Them Softly,111625.0,369.0,English,1.50,2012.0,6.2,20000.0,-0.006143,Crime,Thriller
4749,NaN,Tom DiCillo,10.0,Comedy|Music|Romance,Brad Pitt,Johnny Suede,3013.0,24.0,English,0.05,1991.0,5.8,344.0,NaN,Comedy,Music
2333,0.053101,Angelina Jolie Pitt,131.0,Drama|Romance,Brad Pitt,By the Sea,7976.0,61.0,English,1.00,2015.0,5.3,0.0,-0.946899,Drama,Romance

In [29]:
# Write your code for grouping the combined dataframe here
movies_by_lead = combined.groupby('actor_1_name')

In [30]:
# Write the code for finding the mean of critic reviews and audience reviews here
print(movies_by_lead["num_critic_for_reviews"].mean())
print(movies_by_lead["num_user_for_reviews"].mean())

actor_1_name
Brad Pitt            231.944444
Leonardo DiCaprio    330.190476
Name: num_critic_for_reviews, dtype: float64
actor_1_name
Brad Pitt            702.444444
Leonardo DiCaprio    914.476190
Name: num_user_for_reviews, dtype: float64

**Checkpoint 6:** `Leonardo` has aced both the lists!